// ─── AGRI STORE MOCK DATA ───────────────────────────────────────────────────

export const CATEGORIES = [
  { id: '1', name: 'Fertilizers', nameHi: 'खाद', icon: 'leaf', color: '#52B788' },
  { id: '2', name: 'Pesticides', nameHi: 'कीटनाशक', icon: 'bug', color: '#E76F51' },
  { id: '3', name: 'Machinery', nameHi: 'मशीनरी', icon: 'construct', color: '#4CC9F0' },
  { id: '4', name: 'Seeds', nameHi: 'बीज', icon: 'flower', color: '#FFB703' },
  { id: '5', name: 'Animal Food', nameHi: 'पशु आहार', icon: 'paw', color: '#F4A261' },
];

export const PRODUCTS = [
  // Fertilizers
  {
    id: 'f1', category: '1',
    name: 'DAP Fertilizer (50 kg)',
    nameHi: 'डीएपी खाद (50 किलो)',
    brand: 'IFFCO',
    price: 1350, mrp: 1500,
    rating: 4.5, reviews: 320, ratingCount: 320,
    images: [],
    description: 'Di-Ammonium Phosphate - Best for wheat, rice, and vegetable crops. Boosts root development.',
    inStock: true, unit: 'Bag',
  },
  {
    id: 'f2', category: '1',
    name: 'Urea (50 kg)',
    nameHi: 'यूरिया (50 किलो)',
    brand: 'Chambal Fertilisers',
    price: 266, mrp: 280,
    rating: 4.3, reviews: 580, ratingCount: 580,
    images: [],
    description: 'High nitrogen content fertilizer. Ideal for all kharif and rabi crops.',
    inStock: true, unit: 'Bag',
  },
  {
    id: 'f3', category: '1',
    name: 'Potash (MOP) 50kg',
    nameHi: 'पोटाश (50 किलो)',
    brand: 'IPL',
    price: 1100, mrp: 1200,
    rating: 4.2, reviews: 210, ratingCount: 210,
    images: [],
    description: 'Muriate of Potash for improving crop quality and disease resistance.',
    inStock: true, unit: 'Bag',
  },
  {
    id: 'f4', category: '1',
    name: 'SSP Fertilizer (50 kg)',
    nameHi: 'सिंगल सुपर फॉस्फेट (50 किलो)',
    brand: 'Deepak Fertilisers',
    price: 480, mrp: 540,
    rating: 4.3, reviews: 275, ratingCount: 275,
    images: [],
    description: 'Single Super Phosphate with sulphur. Ideal for oilseeds, pulses and vegetables. Improves soil health.',
    inStock: true, unit: 'Bag',
  },
  {
    id: 'f5', category: '1',
    name: 'NPK 10-26-26 (50 kg)',
    nameHi: 'एनपीके 10-26-26 (50 किलो)',
    brand: 'Coromandel',
    price: 1550, mrp: 1700,
    rating: 4.6, reviews: 412, ratingCount: 412,
    images: [],
    description: 'Complex NPK fertilizer for flowering and fruiting stage. Best for cotton, sugarcane, and horticulture.',
    inStock: true, unit: 'Bag',
  },
  {
    id: 'f6', category: '1',
    name: 'Zinc Sulphate 33% (25 kg)',
    nameHi: 'जिंक सल्फेट 33% (25 किलो)',
    brand: 'GSFC',
    price: 680, mrp: 750,
    rating: 4.4, reviews: 189, ratingCount: 189,
    images: [],
    description: 'Corrects zinc deficiency in paddy, wheat and maize. Increases yield by 15–20%.',
    inStock: true, unit: 'Bag',
  },
  {
    id: 'f7', category: '1',
    name: 'Organic Compost (40 kg)',
    nameHi: 'जैविक खाद (40 किलो)',
    brand: 'Greenway Biotech',
    price: 450, mrp: 500,
    rating: 4.5, reviews: 340, ratingCount: 340,
    images: [],
    description: 'Certified organic compost from cow dung and crop residue. Improves soil texture and microbial activity.',
    inStock: true, unit: 'Bag',
  },
  {
    id: 'f8', category: '1',
    name: 'Micronutrient Mixture (5 kg)',
    nameHi: 'सूक्ष्म पोषक तत्व मिश्रण (5 किलो)',
    brand: 'Multiplex',
    price: 380, mrp: 420,
    rating: 4.2, reviews: 156, ratingCount: 156,
    images: [],
    description: 'Multi-micronutrient (Zn, Fe, Mn, Cu, B, Mo) blend for all crops. Prevents hidden hunger.',
    inStock: true, unit: 'Packet',
  },
  {
    id: 'f9', category: '1',
    name: 'Calcium Ammonium Nitrate (50 kg)',
    nameHi: 'कैल्शियम अमोनियम नाइट्रेट (50 किलो)',
    brand: 'GNFC',
    price: 920, mrp: 1000,
    rating: 4.1, reviews: 130, ratingCount: 130,
    images: [],
    description: 'CAN provides quick-release nitrogen plus calcium. Ideal for potato, tomato and leafy vegetables.',
    inStock: false, unit: 'Bag',
  },
  {
    id: 'f10', category: '1',
    name: 'Sulphur 90% WDG (25 kg)',
    nameHi: 'सल्फर 90% WDG (25 किलो)',
    brand: 'Coromandel',
    price: 850, mrp: 950,
    rating: 4.4, reviews: 220, ratingCount: 220,
    images: [],
    description: 'Water-dispersible granule sulphur. Corrects sulphur deficiency, controls powdery mildew. Used in oilseeds.',
    inStock: true, unit: 'Bag',
  },
  // Pesticides
  {
    id: 'p1', category: '2',
    name: 'Chlorpyrifos 20% EC',
    nameHi: 'क्लोरपाइरीफोस',
    brand: 'Dhanuka',
    price: 280, mrp: 320,
    rating: 4.4, reviews: 195, ratingCount: 195,
    images: [],
    description: 'Broad spectrum insecticide for termites, white grubs in soil.',
    inStock: true, unit: 'Litre',
  },
  {
    id: 'p2', category: '2',
    name: 'Mancozeb 75% WP',
    nameHi: 'मैंकोजेब',
    brand: 'Indofil',
    price: 160, mrp: 180,
    rating: 4.1, reviews: 145, ratingCount: 145,
    images: [],
    description: 'Protective fungicide for blight, leaf spot in tomato, potato.',
    inStock: true, unit: 'Kg',
  },
  {
    id: 'p3', category: '2',
    name: 'Glyphosate 41% SL (1 Litre)',
    nameHi: 'ग्लाइफोसेट 41% SL (1 लीटर)',
    brand: 'Bayer',
    price: 320, mrp: 370,
    rating: 4.5, reviews: 380, ratingCount: 380,
    images: [],
    description: 'Systemic herbicide for control of grasses and broadleaf weeds. Non-selective post-emergence.',
    inStock: true, unit: 'Litre',
  },
  {
    id: 'p4', category: '2',
    name: 'Imidacloprid 17.8% SL (100ml)',
    nameHi: 'इमिडाक्लोप्रिड 17.8% SL (100 मिली)',
    brand: 'Bayer (Confidor)',
    price: 240, mrp: 280,
    rating: 4.6, reviews: 510, ratingCount: 510,
    images: [],
    description: 'Systemic insecticide for sucking pests — aphids, whitefly, thrips, jassids in cotton and vegetables.',
    inStock: true, unit: '100ml Bottle',
  },
  {
    id: 'p5', category: '2',
    name: 'Carbendazim 50% WP (500g)',
    nameHi: 'कार्बेंडाज़िम 50% WP (500 ग्राम)',
    brand: 'UPL',
    price: 185, mrp: 210,
    rating: 4.3, reviews: 290, ratingCount: 290,
    images: [],
    description: 'Systemic fungicide for powdery mildew, loose smut, and collar rot in cereals and vegetables.',
    inStock: true, unit: '500g Packet',
  },
  {
    id: 'p6', category: '2',
    name: 'Lambda-Cyhalothrin 5% EC (1L)',
    nameHi: 'लैम्बडा-साइहेलोथ्रिन 5% EC (1 लीटर)',
    brand: 'Syngenta (Karate)',
    price: 420, mrp: 480,
    rating: 4.4, reviews: 175, ratingCount: 175,
    images: [],
    description: 'Broad-spectrum pyrethroid insecticide. Fast knockdown action on caterpillars, bollworm, pod borers.',
    inStock: true, unit: 'Litre',
  },
  {
    id: 'p7', category: '2',
    name: 'Propiconazole 25% EC (250ml)',
    nameHi: 'प्रोपिकोनाज़ोल 25% EC (250 मिली)',
    brand: 'Syngenta (Tilt)',
    price: 310, mrp: 360,
    rating: 4.5, reviews: 245, ratingCount: 245,
    images: [],
    description: 'Systemic fungicide for rust, sheath blight and powdery mildew in wheat, rice and groundnut.',
    inStock: true, unit: '250ml Bottle',
  },
  {
    id: 'p8', category: '2',
    name: 'Emamectin Benzoate 5% SG (100g)',
    nameHi: 'इमामेक्टिन बेंजोएट 5% SG (100 ग्राम)',
    brand: 'Dhanuka (Emactin)',
    price: 270, mrp: 310,
    rating: 4.6, reviews: 198, ratingCount: 198,
    images: [],
    description: 'Highly effective insecticide for diamond-back moth, fall armyworm, and fruit borer.',
    inStock: true, unit: '100g Packet',
  },
  {
    id: 'p9', category: '2',
    name: 'Pendimethalin 30% EC (1 Litre)',
    nameHi: 'पेंडीमेथालिन 30% EC (1 लीटर)',
    brand: 'BASF',
    price: 390, mrp: 440,
    rating: 4.2, reviews: 162, ratingCount: 162,
    images: [],
    description: 'Pre-emergence herbicide for grass and broadleaf weeds in wheat, maize, cotton, and groundnut.',
    inStock: true, unit: 'Litre',
  },
  {
    id: 'p10', category: '2',
    name: 'Azoxystrobin 23% SC (250ml)',
    nameHi: 'एज़ोक्सीस्ट्रोबिन 23% SC (250 मिली)',
    brand: 'Syngenta (Amistar)',
    price: 520, mrp: 600,
    rating: 4.7, reviews: 330, ratingCount: 330,
    images: [],
    description: 'Strobilurin fungicide for rice blast, powdery mildew, and anthracnose in multiple crops.',
    inStock: false, unit: '250ml Bottle',
  },
  // Machinery
  {
    id: 'm1', category: '3',
    name: 'Electric Spray Pump',
    nameHi: 'इलेक्ट्रिक स्प्रेयर',
    brand: 'Aspee',
    price: 4500, mrp: 5200,
    rating: 4.6, reviews: 430, ratingCount: 430,
    images: [],
    description: '16L battery-powered knapsack sprayer. 8-hour battery life. Lightweight design.',
    inStock: true, unit: 'Piece',
  },
  {
    id: 'm2', category: '3',
    name: 'Hand Weeder Set',
    nameHi: 'हाथ निराई सेट',
    brand: 'Agripro',
    price: 380, mrp: 450,
    rating: 4.0, reviews: 85, ratingCount: 85,
    images: [],
    description: 'Set of 5 ergonomic hand tools for weeding and soil loosening.',
    inStock: true, unit: 'Set',
  },
  // Seeds
  {
    id: 's1', category: '4',
    name: 'Hybrid Tomato Seeds',
    nameHi: 'हाइब्रिड टमाटर बीज',
    brand: 'Mahyco',
    price: 120, mrp: 145,
    rating: 4.7, reviews: 560, ratingCount: 560,
    images: [],
    description: 'High-yield hybrid variety. 90-day crop. Disease resistant.',
    inStock: true, unit: '10g Packet',
  },
  {
    id: 's2', category: '4',
    name: 'Paddy Seeds (IR-36)',
    nameHi: 'धान के बीज (IR-36)',
    brand: 'NSC',
    price: 55, mrp: 65,
    rating: 4.5, reviews: 720, ratingCount: 720,
    images: [],
    description: 'Short duration, high-yielding paddy variety. 105-day crop. Semi-dwarf.',
    inStock: true, unit: 'Kg',
  },
  {
    id: 's3', category: '4',
    name: 'Wheat Seeds HD-2967 (5 kg)',
    nameHi: 'गेहूं बीज HD-2967 (5 किलो)',
    brand: 'NSC',
    price: 180, mrp: 210,
    rating: 4.6, reviews: 890, ratingCount: 890,
    images: [],
    description: 'High-yielding wheat variety HD-2967. Resistant to brown rust. Ideal for North India rabi season.',
    inStock: true, unit: '5kg Bag',
  },
  {
    id: 's4', category: '4',
    name: 'Cotton Bt Seeds (450g)',
    nameHi: 'कपास बीटी बीज (450 ग्राम)',
    brand: 'Mahyco',
    price: 730, mrp: 830,
    rating: 4.4, reviews: 420, ratingCount: 420,
    images: [],
    description: 'Bt cotton hybrid with bollworm resistance. High ginning outturn. 160-day variety for kharif season.',
    inStock: true, unit: 'Packet',
  },
  {
    id: 's5', category: '4',
    name: 'Mustard Seeds PM-25 (1 kg)',
    nameHi: 'सरसों बीज PM-25 (1 किलो)',
    brand: 'NRCRM',
    price: 95, mrp: 110,
    rating: 4.3, reviews: 315, ratingCount: 315,
    images: [],
    description: 'Improved mustard variety PM-25. High oil content (42%), tolerant to Sclerotinia rot.',
    inStock: true, unit: 'Kg',
  },
  {
    id: 's6', category: '4',
    name: 'Chilli Seeds Pusa Jwala (50g)',
    nameHi: 'मिर्च बीज पूसा ज्वाला (50 ग्राम)',
    brand: 'IARI',
    price: 65, mrp: 80,
    rating: 4.5, reviews: 440, ratingCount: 440,
    images: [],
    description: 'Long, thin, highly pungent chilli variety. 3000–4000 fruits per plant. 90-day bearing.',
    inStock: true, unit: '50g Packet',
  },
  {
    id: 's7', category: '4',
    name: 'Watermelon Hybrid Seeds (50g)',
    nameHi: 'तरबूज हाइब्रिड बीज (50 ग्राम)',
    brand: 'Syngenta',
    price: 140, mrp: 165,
    rating: 4.6, reviews: 275, ratingCount: 275,
    images: [],
    description: 'Seedless hybrid watermelon. 8–10 kg fruit weight. 75-day crop. Excellent shelf life.',
    inStock: true, unit: '50g Packet',
  },
  {
    id: 's8', category: '4',
    name: 'Maize Hybrid DHM-117 (5 kg)',
    nameHi: 'मक्का हाइब्रिड DHM-117 (5 किलो)',
    brand: 'DuPont Pioneer',
    price: 520, mrp: 600,
    rating: 4.7, reviews: 610, ratingCount: 610,
    images: [],
    description: 'High-yielding maize hybrid DHM-117. 8–9 tonne/acre yield. Drought tolerant, blight resistant.',
    inStock: true, unit: '5kg Bag',
  },
  {
    id: 's9', category: '4',
    name: 'Onion Seeds Agrifound (500g)',
    nameHi: 'प्याज बीज एग्रीफाउंड (500 ग्राम)',
    brand: 'NHRDF',
    price: 220, mrp: 260,
    rating: 4.4, reviews: 365, ratingCount: 365,
    images: [],
    description: 'Agrifound Dark Red onion variety. 120-day crop. High bulb size, deep red color, long storage.',
    inStock: true, unit: '500g Packet',
  },
  {
    id: 's10', category: '4',
    name: 'Soybean Seeds JS-335 (30 kg)',
    nameHi: 'सोयाबीन बीज JS-335 (30 किलो)',
    brand: 'MPKV',
    price: 1350, mrp: 1500,
    rating: 4.3, reviews: 480, ratingCount: 480,
    images: [],
    description: 'Medium-duration soybean JS-335. 95-day crop. High protein content. Suitable for central India.',
    inStock: true, unit: '30kg Bag',
  },
  // Animal Food
  {
    id: 'a1', category: '5',
    name: 'Cattle Feed (50 kg)',
    nameHi: 'पशु आहार (50 किलो)',
    brand: 'Godrej Agrovet',
    price: 1200, mrp: 1350,
    rating: 4.6, reviews: 380, ratingCount: 380,
    images: [],
    description: 'Balanced nutrition for dairy cows. Improves milk yield by up to 15%.',
    inStock: true, unit: 'Bag',
  },
  {
    id: 'a2', category: '5',
    name: 'Poultry Feed (25 kg)',
    nameHi: 'मुर्गी आहार (25 किलो)',
    brand: 'Venkateshwara',
    price: 850, mrp: 950,
    rating: 4.3, reviews: 210, ratingCount: 210,
    images: [],
    description: 'Complete layer feed for egg-laying hens. High protein formula.',
    inStock: true, unit: 'Bag',
  },
];

// ─── ANIMAL TRADE MOCK DATA ──────────────────────────────────────────────────

export const ANIMAL_LISTINGS = [
  {
    id: 'al1', lat: 19.9975, lng: 73.7898,
    sellerName: 'Ramesh Kumar',
    sellerPhone: '9876543210',
    sellerLocation: 'Nashik, Maharashtra',
    sellerAvatar: 'RK',
    animal: 'Cow',
    animalHi: 'गाय',
    breed: 'Gir',
    age: '4 years',
    gender: 'Female',
    weight: '350 kg',
    milkYield: '12 Litre/Day',
    vaccinated: true,
    price: 55000,
    description: 'Healthy Gir cow, excellent milk producer. Fully vaccinated. Gentle temperament, easy to handle.',
    images: [],
    postedDate: '2 days ago',
    verified: true,
    tags: ['Vaccinated', 'High Milk Yield', 'Healthy'],
  },
  {
    id: 'al2', lat: 22.5645, lng: 72.9289,
    sellerName: 'Suresh Patel',
    sellerPhone: '9123456780',
    sellerLocation: 'Anand, Gujarat',
    sellerAvatar: 'SP',
    animal: 'Buffalo',
    animalHi: 'भैंस',
    breed: 'Murrah',
    age: '5 years',
    gender: 'Female',
    weight: '480 kg',
    milkYield: '16 Litre/Day',
    vaccinated: true,
    price: 75000,
    description: 'Top quality Murrah buffalo. Highest milk fat content. Good for dairy business.',
    images: [],
    postedDate: '1 day ago',
    verified: true,
    tags: ['High Fat Milk', 'Vaccinated', 'Premium'],
  },
  {
    id: 'al3', lat: 30.9010, lng: 75.8573,
    sellerName: 'Mohan Singh',
    sellerPhone: '8765432109',
    sellerLocation: 'Ludhiana, Punjab',
    sellerAvatar: 'MS',
    animal: 'Goat',
    animalHi: 'बकरी',
    breed: 'Beetal',
    age: '2 years',
    gender: 'Female',
    weight: '35 kg',
    milkYield: '2 Litre/Day',
    vaccinated: false,
    price: 8500,
    description: 'Healthy Beetal goat. Good for milk and meat both. Pair available.',
    images: [],
    postedDate: '3 days ago',
    verified: false,
    tags: ['Dual Purpose', 'Healthy'],
  },
  {
    id: 'al4', lat: 25.5941, lng: 85.1376,
    sellerName: 'Dilip Yadav',
    sellerPhone: '7654321098',
    sellerLocation: 'Patna, Bihar',
    sellerAvatar: 'DY',
    animal: 'Bullock',
    animalHi: 'बैल',
    breed: 'Sahiwal',
    age: '6 years',
    gender: 'Male',
    weight: '400 kg',
    milkYield: 'N/A',
    vaccinated: true,
    price: 45000,
    description: 'Strong pair of Sahiwal bullocks, trained for farming. Used 3 seasons. Still strong.',
    images: [],
    postedDate: '5 days ago',
    verified: true,
    tags: ['Farm Trained', 'Strong', 'Pair Available'],
  },
  // More Cows
  {
    id: 'al5', lat: 16.7050, lng: 74.2433,
    sellerName: 'Pravin Jadhav',
    sellerPhone: '9823001234',
    sellerLocation: 'Kolhapur, Maharashtra',
    sellerAvatar: 'PJ',
    animal: 'Cow',
    animalHi: 'गाय',
    breed: 'HF (Holstein Friesian)',
    age: '3 years',
    gender: 'Female',
    weight: '420 kg',
    milkYield: '20 Litre/Day',
    vaccinated: true,
    price: 85000,
    description: 'Pure HF cow with exceptional milk yield. Imported lineage. Ideal for commercial dairy farms.',
    images: [],
    postedDate: '1 day ago',
    verified: true,
    tags: ['High Milk Yield', 'Imported Breed', 'Vaccinated'],
    topRated: true,
  },
  {
    id: 'al6', lat: 10.5276, lng: 76.2144,
    sellerName: 'Sanjay Nair',
    sellerPhone: '9034567890',
    sellerLocation: 'Thrissur, Kerala',
    sellerAvatar: 'SN',
    animal: 'Cow',
    animalHi: 'गाय',
    breed: 'Jersey Cross',
    age: '4 years',
    gender: 'Female',
    weight: '300 kg',
    milkYield: '14 Litre/Day',
    vaccinated: true,
    price: 48000,
    description: 'Jersey cross-bred cow, well-adapted to tropical climate. High fat milk, excellent for ghee making.',
    images: [],
    postedDate: '2 days ago',
    verified: true,
    tags: ['High Fat Milk', 'Vaccinated', 'Tropical Adapted'],
  },
  {
    id: 'al7', lat: 31.6340, lng: 74.8723,
    sellerName: 'Harpreet Singh',
    sellerPhone: '9812345678',
    sellerLocation: 'Amritsar, Punjab',
    sellerAvatar: 'HS',
    animal: 'Cow',
    animalHi: 'गाय',
    breed: 'Sahiwal',
    age: '5 years',
    gender: 'Female',
    weight: '380 kg',
    milkYield: '10 Litre/Day',
    vaccinated: true,
    price: 62000,
    description: 'Pure desi Sahiwal cow, heat tolerant and tick resistant. Low-cost maintenance. Good for organic farming.',
    images: [],
    postedDate: '4 days ago',
    verified: true,
    tags: ['Desi Breed', 'Low Maintenance', 'Heat Tolerant'],
  },
  {
    id: 'al8', lat: 26.2389, lng: 73.0243,
    sellerName: 'Manohar Rathore',
    sellerPhone: '9887654321',
    sellerLocation: 'Jodhpur, Rajasthan',
    sellerAvatar: 'MR',
    animal: 'Cow',
    animalHi: 'गाय',
    breed: 'Tharparkar',
    age: '4 years',
    gender: 'Female',
    weight: '320 kg',
    milkYield: '8 Litre/Day',
    vaccinated: true,
    price: 40000,
    description: 'Native Tharparkar cow, drought-resistant. Good milk quality with A2 beta-casein protein.',
    images: [],
    postedDate: '6 days ago',
    verified: false,
    tags: ['A2 Milk', 'Drought Resistant', 'Desi Breed'],
  },
  {
    id: 'al9', lat: 16.3067, lng: 80.4365,
    sellerName: 'Venkatesh Rao',
    sellerPhone: '9966778899',
    sellerLocation: 'Guntur, Andhra Pradesh',
    sellerAvatar: 'VR',
    animal: 'Cow',
    animalHi: 'गाय',
    breed: 'Ongole',
    age: '6 years',
    gender: 'Female',
    weight: '450 kg',
    milkYield: '7 Litre/Day',
    vaccinated: true,
    price: 38000,
    description: 'Famous Ongole breed, highly disease-resistant. Strong build. Ideal for mixed farming.',
    images: [],
    postedDate: '1 week ago',
    verified: true,
    tags: ['Disease Resistant', 'Strong Build', 'Desi Breed'],
  },
  {
    id: 'al10', lat: 17.3850, lng: 78.4867,
    sellerName: 'Imran Khan',
    sellerPhone: '9911223344',
    sellerLocation: 'Hyderabad, Telangana',
    sellerAvatar: 'IK',
    animal: 'Cow',
    animalHi: 'गाय',
    breed: 'Red Sindhi',
    age: '3 years',
    gender: 'Female',
    weight: '290 kg',
    milkYield: '9 Litre/Day',
    vaccinated: false,
    price: 36000,
    description: 'Red Sindhi cow with good milk fat (5%). Adaptable to dry climates, low feed requirement.',
    images: [],
    postedDate: '3 days ago',
    verified: false,
    tags: ['Low Feed Requirement', 'High Fat Milk'],
  },
  {
    id: 'al11', lat: 23.2420, lng: 69.6669,
    sellerName: 'Jayesh Prajapati',
    sellerPhone: '9876012345',
    sellerLocation: 'Bhuj, Gujarat',
    sellerAvatar: 'JP',
    animal: 'Cow',
    animalHi: 'गाय',
    breed: 'Kankrej',
    age: '5 years',
    gender: 'Female',
    weight: '400 kg',
    milkYield: '6 Litre/Day',
    vaccinated: true,
    price: 42000,
    description: 'Kankrej dual-purpose breed, excellent for both milk and draft work. Strong, long-lived animal.',
    images: [],
    postedDate: '5 days ago',
    verified: true,
    tags: ['Dual Purpose', 'Strong', 'Long Lived'],
  },
  {
    id: 'al12', lat: 18.4088, lng: 76.5604,
    sellerName: 'Raghunath Deshmukh',
    sellerPhone: '9955443322',
    sellerLocation: 'Latur, Maharashtra',
    sellerAvatar: 'RD',
    animal: 'Cow',
    animalHi: 'गाय',
    breed: 'Deoni',
    age: '4 years',
    gender: 'Female',
    weight: '360 kg',
    milkYield: '8 Litre/Day',
    vaccinated: true,
    price: 44000,
    description: 'Deoni breed native to Marathwada. Good milk quality, well-adapted to Deccan plateau climate.',
    images: [],
    postedDate: '2 days ago',
    verified: true,
    tags: ['Local Breed', 'Climate Adapted', 'Vaccinated'],
  },
  {
    id: 'al13', lat: 29.6857, lng: 76.9905,
    sellerName: 'Rohit Sharma',
    sellerPhone: '9800112233',
    sellerLocation: 'Karnal, Haryana',
    sellerAvatar: 'RS',
    animal: 'Cow',
    animalHi: 'गाय',
    breed: 'Hariana',
    age: '4 years',
    gender: 'Female',
    weight: '340 kg',
    milkYield: '7 Litre/Day',
    vaccinated: true,
    price: 39000,
    description: 'Native Hariana breed, famous in North India. Good draft capability, suitable for small farmers.',
    images: [],
    postedDate: '3 days ago',
    verified: false,
    tags: ['Draft Capable', 'Desi Breed', 'Hardy'],
  },
  // Buffaloes
  {
    id: 'al14', lat: 21.1702, lng: 72.8311,
    sellerName: 'Kantilal Shah',
    sellerPhone: '9898765432',
    sellerLocation: 'Surat, Gujarat',
    sellerAvatar: 'KS',
    animal: 'Buffalo',
    animalHi: 'भैंस',
    breed: 'Surti',
    age: '4 years',
    gender: 'Female',
    weight: '410 kg',
    milkYield: '10 Litre/Day',
    vaccinated: true,
    price: 52000,
    description: 'Surti buffalo with good fat percentage (7.5%). Popular in Gujarat, easy to manage and maintain.',
    images: [],
    postedDate: '2 days ago',
    verified: true,
    tags: ['High Fat Milk', 'Vaccinated', 'Easy to Manage'],
  },
  {
    id: 'al15', lat: 30.9290, lng: 74.6127,
    sellerName: 'Amarjit Sandhu',
    sellerPhone: '9876567890',
    sellerLocation: 'Ferozepur, Punjab',
    sellerAvatar: 'AS',
    animal: 'Buffalo',
    animalHi: 'भैंस',
    breed: 'Nili-Ravi',
    age: '5 years',
    gender: 'Female',
    weight: '520 kg',
    milkYield: '18 Litre/Day',
    vaccinated: true,
    price: 90000,
    description: 'Top-grade Nili-Ravi buffalo from Punjab. Record milk yields. Best for commercial dairy operations.',
    images: [],
    postedDate: '1 day ago',
    verified: true,
    tags: ['Record Milk Yield', 'Premium', 'Vaccinated'],
    topRated: true,
  },
  {
    id: 'al16', lat: 22.4707, lng: 70.0577,
    sellerName: 'Bhavesh Gohil',
    sellerPhone: '9854321076',
    sellerLocation: 'Jamnagar, Gujarat',
    sellerAvatar: 'BG',
    animal: 'Buffalo',
    animalHi: 'भैंस',
    breed: 'Jaffarabadi',
    age: '6 years',
    gender: 'Female',
    weight: '600 kg',
    milkYield: '20 Litre/Day',
    vaccinated: true,
    price: 110000,
    description: 'Heaviest buffalo breed from Gir forest. Exceptional milk yield. Prized for commercial dairy production.',
    images: [],
    postedDate: '4 days ago',
    verified: true,
    tags: ['Highest Milk Yield', 'Heavy Build', 'Premium'],
  },
  {
    id: 'al17', lat: 27.1767, lng: 78.0081,
    sellerName: 'Umesh Agarwal',
    sellerPhone: '9922334455',
    sellerLocation: 'Agra, Uttar Pradesh',
    sellerAvatar: 'UA',
    animal: 'Buffalo',
    animalHi: 'भैंस',
    breed: 'Bhadawari',
    age: '4 years',
    gender: 'Female',
    weight: '380 kg',
    milkYield: '7 Litre/Day',
    vaccinated: false,
    price: 38000,
    description: 'Bhadawari buffalo, highest fat content (13%) in India. Prized for ghee and khoya production.',
    images: [],
    postedDate: '5 days ago',
    verified: false,
    tags: ['Highest Fat Content', 'Ghee Ideal', 'Desi Breed'],
  },
  {
    id: 'al18', lat: 17.6806, lng: 75.3280,
    sellerName: 'Siddharth Kulkarni',
    sellerPhone: '9744556677',
    sellerLocation: 'Pandharpur, Maharashtra',
    sellerAvatar: 'SK',
    animal: 'Buffalo',
    animalHi: 'भैंस',
    breed: 'Pandharpuri',
    age: '3 years',
    gender: 'Female',
    weight: '440 kg',
    milkYield: '12 Litre/Day',
    vaccinated: true,
    price: 58000,
    description: 'Pandharpuri breed from Maharashtra. Good milk yield with 7% fat, well-adapted to local climate.',
    images: [],
    postedDate: '3 days ago',
    verified: true,
    tags: ['Local Breed', 'High Fat', 'Vaccinated'],
  },
  {
    id: 'al19', lat: 21.1458, lng: 79.0882,
    sellerName: 'Nilesh Wankhede',
    sellerPhone: '9633224455',
    sellerLocation: 'Nagpur, Maharashtra',
    sellerAvatar: 'NW',
    animal: 'Buffalo',
    animalHi: 'भैंस',
    breed: 'Nagpuri',
    age: '5 years',
    gender: 'Female',
    weight: '470 kg',
    milkYield: '11 Litre/Day',
    vaccinated: true,
    price: 55000,
    description: 'Nagpuri buffalo, well-adapted to Vidarbha climate. Good for both milk and draft work.',
    images: [],
    postedDate: '2 days ago',
    verified: true,
    tags: ['Dual Purpose', 'Climate Adapted', 'Vaccinated'],
  },
  {
    id: 'al20', lat: 23.5880, lng: 72.3693,
    sellerName: 'Dharmesh Patel',
    sellerPhone: '9512345678',
    sellerLocation: 'Mehsana, Gujarat',
    sellerAvatar: 'DP',
    animal: 'Buffalo',
    animalHi: 'भैंस',
    breed: 'Mehsani',
    age: '4 years',
    gender: 'Female',
    weight: '450 kg',
    milkYield: '14 Litre/Day',
    vaccinated: true,
    price: 68000,
    description: 'Popular Mehsani buffalo from North Gujarat. High productivity, widely used in commercial dairies.',
    images: [],
    postedDate: '1 day ago',
    verified: true,
    tags: ['Commercial Dairy', 'High Productivity', 'Vaccinated'],
  },
  {
    id: 'al21', lat: 11.4916, lng: 76.7337,
    sellerName: 'Krishnamurthy T',
    sellerPhone: '9788990011',
    sellerLocation: 'Nilgiris, Tamil Nadu',
    sellerAvatar: 'KT',
    animal: 'Buffalo',
    animalHi: 'भैंस',
    breed: 'Toda',
    age: '5 years',
    gender: 'Female',
    weight: '350 kg',
    milkYield: '5 Litre/Day',
    vaccinated: false,
    price: 28000,
    description: 'Rare Toda buffalo from Nilgiri hills. Produces thick, rich milk. Hardy hill-adapted breed.',
    images: [],
    postedDate: '1 week ago',
    verified: false,
    tags: ['Rare Breed', 'Rich Milk', 'Hill Adapted'],
  },
  {
    id: 'al22', lat: 20.2961, lng: 85.8245,
    sellerName: 'Bikash Mohanty',
    sellerPhone: '9437890123',
    sellerLocation: 'Bhubaneswar, Odisha',
    sellerAvatar: 'BM',
    animal: 'Buffalo',
    animalHi: 'भैंस',
    breed: 'Chilika',
    age: '4 years',
    gender: 'Female',
    weight: '370 kg',
    milkYield: '6 Litre/Day',
    vaccinated: true,
    price: 32000,
    description: 'Chilika breed from Odisha, grazes on wetland vegetation. Hardy, disease-resistant, low-cost rearing.',
    images: [],
    postedDate: '6 days ago',
    verified: true,
    tags: ['Hardy', 'Disease Resistant', 'Low Cost Rearing'],
  },
  // ── Near Pune listings (for distance filter demo) ──
  {
    id: 'al23', lat: 18.4999, lng: 73.9299,
    sellerName: 'Ganesh Shinde',
    sellerPhone: '9823456701',
    sellerLocation: 'Hadapsar, Pune',
    sellerAvatar: 'GS',
    animal: 'Cow',
    animalHi: 'गाय',
    breed: 'Gir',
    age: '3 years',
    gender: 'Female',
    weight: '330 kg',
    milkYield: '10 Litre/Day',
    vaccinated: true,
    price: 52000,
    description: 'Healthy Gir cow from Hadapsar. Fully vaccinated, good temperament, easy to handle.',
    images: [],
    postedDate: '1 day ago',
    verified: true,
    tags: ['Vaccinated', 'Healthy', 'Near Pune'],
  },
  {
    id: 'al24', lat: 18.6279, lng: 73.8031,
    sellerName: 'Sachin Pawar',
    sellerPhone: '9876540012',
    sellerLocation: 'Pimpri-Chinchwad, Pune',
    sellerAvatar: 'SP',
    animal: 'Buffalo',
    animalHi: 'भैंस',
    breed: 'Murrah',
    age: '4 years',
    gender: 'Female',
    weight: '460 kg',
    milkYield: '15 Litre/Day',
    vaccinated: true,
    price: 72000,
    description: 'Premium Murrah buffalo, high milk fat. Based in Pimpri-Chinchwad, easy pickup.',
    images: [],
    postedDate: '2 days ago',
    verified: true,
    tags: ['High Fat Milk', 'Vaccinated', 'Near Pune'],
    topRated: true,
  },
  {
    id: 'al25', lat: 18.7350, lng: 73.6800,
    sellerName: 'Vitthal More',
    sellerPhone: '9765432180',
    sellerLocation: 'Talegaon, Pune',
    sellerAvatar: 'VM',
    animal: 'Goat',
    animalHi: 'बकरी',
    breed: 'Osmanabadi',
    age: '2 years',
    gender: 'Female',
    weight: '30 kg',
    milkYield: '1.5 Litre/Day',
    vaccinated: true,
    price: 9500,
    description: 'Osmanabadi goat, Maharashtra\'s local breed. Healthy, good for both milk and meat.',
    images: [],
    postedDate: '3 days ago',
    verified: false,
    tags: ['Local Breed', 'Dual Purpose', 'Vaccinated'],
  },
  {
    id: 'al26', lat: 18.7546, lng: 73.4062,
    sellerName: 'Prakash Desai',
    sellerPhone: '9654321087',
    sellerLocation: 'Lonavala, Pune',
    sellerAvatar: 'PD',
    animal: 'Cow',
    animalHi: 'गाय',
    breed: 'Jersey Cross',
    age: '5 years',
    gender: 'Female',
    weight: '350 kg',
    milkYield: '13 Litre/Day',
    vaccinated: true,
    price: 46000,
    description: 'Jersey cross cow from Lonavala hillside. Well-fed on green pastures, excellent milk quality.',
    images: [],
    postedDate: '4 days ago',
    verified: true,
    tags: ['Hill Grazing', 'Vaccinated', 'Good Milk'],
  },
  {
    id: 'al27', lat: 18.1518, lng: 74.5800,
    sellerName: 'Dattatray Jadhav',
    sellerPhone: '9543210876',
    sellerLocation: 'Baramati, Pune',
    sellerAvatar: 'DJ',
    animal: 'Bullock',
    animalHi: 'बैल',
    breed: 'Khillari',
    age: '5 years',
    gender: 'Male',
    weight: '380 kg',
    milkYield: 'N/A',
    vaccinated: true,
    price: 40000,
    description: 'Strong Khillari bullock pair from Baramati. Trained for farm work, 3 seasons experience.',
    images: [],
    postedDate: '2 days ago',
    verified: true,
    tags: ['Farm Trained', 'Strong', 'Local Breed'],
  },
];

// ─── MACHINERY RENT MOCK DATA ─────────────────────────────────────────────────

export const MACHINERY_LISTINGS = [
  {
    id: 'mr1',
    ownerName: 'Bharat Enterprises',
    ownerPhone: '9900112233',
    location: 'Pune, Maharashtra',
    equipment: 'Tractor (45 HP)',
    category: 'tractor',
    equipmentHi: 'ट्रैक्टर (45 HP)',
    brand: 'Mahindra 575',
    pricePerAcre: 600,
    pricePerHour: 500,
    availability: 'Available Now',
    images: [],
    rating: 4.7, reviews: 125, ratingCount: 125,
    features: ['Ploughing', 'Tilling', 'Sowing', 'Transport'],
    description: 'Well-maintained Mahindra 575 DI tractor with all attachments. Available with driver.',
  },
  {
    id: 'mr2',
    ownerName: 'Kishan Farm Services',
    ownerPhone: '8811223344',
    location: 'Nagpur, Maharashtra',
    equipment: 'Combine Harvester',
    category: 'harvester',
    equipmentHi: 'कम्बाइन हार्वेस्टर',
    brand: 'John Deere W70',
    pricePerAcre: 1800,
    pricePerHour: 2500,
    availability: 'Available from Oct 15',
    images: [],
    rating: 4.8, reviews: 89, ratingCount: 89,
    features: ['Wheat Harvesting', 'Soybean', 'Paddy'],
    description: 'Modern combine harvester. Fast harvesting, minimal grain loss. GPS enabled.',
  },
  {
    id: 'mr3',
    ownerName: 'Agro Solutions',
    ownerPhone: '7722334455',
    location: 'Aurangabad, Maharashtra',
    equipment: 'Rotavator',
    category: 'rotavator',
    equipmentHi: 'रोटावेटर',
    brand: 'Fieldking FR-200',
    pricePerAcre: 350,
    pricePerHour: 400,
    availability: 'Available Now',
    images: [],
    rating: 4.5, reviews: 67, ratingCount: 67,
    features: ['Soil Preparation', 'Weed Removal', 'Stubble Management'],
    description: 'Heavy-duty rotavator. Excellent for primary and secondary tillage.',
  },
  {
    id: 'mr4',
    ownerName: 'Kissan Seva Kendra',
    ownerPhone: '6633445566',
    location: 'Solapur, Maharashtra',
    equipment: 'Paddy Transplanter',
    category: 'transplanter',
    equipmentHi: 'धान रोपाई मशीन',
    brand: 'Kubota NSP-8W',
    pricePerAcre: 900,
    pricePerHour: 1200,
    availability: 'Available Now',
    images: [],
    rating: 4.3, reviews: 45, ratingCount: 45,
    features: ['8-Row Transplanting', 'GPS Guided', 'Adjustable Spacing'],
    description: 'Self-propelled 8-row paddy transplanter. Saves 70% labour cost vs manual planting.',
  },
  // More Tractors
  {
    id: 'mr5',
    ownerName: 'Agri Rental Hub',
    ownerPhone: '9800233455',
    location: 'Amravati, Maharashtra',
    equipment: 'Tractor (50 HP)',
    category: 'tractor',
    equipmentHi: 'ट्रैक्टर (50 HP)',
    brand: 'John Deere 5050D',
    pricePerAcre: 650,
    pricePerHour: 550,
    availability: 'Available Now',
    images: [],
    rating: 4.9, reviews: 210, ratingCount: 210,
    features: ['Ploughing', 'Tilling', 'Sowing', 'Harvesting Support'],
    description: 'Fuel-efficient John Deere 5050D with power steering. GPS enabled. Available with all implements.',
  },
  {
    id: 'mr6',
    ownerName: 'Kisaan Tech Services',
    ownerPhone: '9711445566',
    location: 'Ludhiana, Punjab',
    equipment: 'Tractor (75 HP)',
    category: 'tractor',
    equipmentHi: 'ट्रैक्टर (75 HP)',
    brand: 'Sonalika GT 750',
    pricePerAcre: 850,
    pricePerHour: 700,
    availability: 'Available from Nov 5',
    images: [],
    rating: 4.7, reviews: 88, ratingCount: 88,
    features: ['Heavy Ploughing', 'Sub-Soiling', '4WD', 'Transport'],
    description: 'Heavy-duty Sonalika 75 HP tractor with 4-wheel drive. Ideal for hard, clay soils.',
  },
  {
    id: 'mr7',
    ownerName: 'Farmer Friends Co-op',
    ownerPhone: '9622778899',
    location: 'Coimbatore, Tamil Nadu',
    equipment: 'Tractor (45 HP)',
    equipmentHi: 'ट्रैक्टर (45 HP)',
    brand: 'TAFE 45DI',
    pricePerAcre: 580,
    pricePerHour: 490,
    availability: 'Available Now',
    images: [],
    rating: 4.5, reviews: 132, ratingCount: 132,
    features: ['Ploughing', 'Tilling', 'Sowing', 'Spraying'],
    description: 'Reliable TAFE tractor with excellent fuel economy. Suitable for paddy and sugarcane fields.',
  },
  {
    id: 'mr8',
    ownerName: 'Shree Agro Services',
    ownerPhone: '9533889900',
    location: 'Nashik, Maharashtra',
    equipment: 'Tractor (55 HP)',
    category: 'tractor',
    equipmentHi: 'ट्रैक्टर (55 HP)',
    brand: 'New Holland 3630 TX Plus',
    pricePerAcre: 720,
    pricePerHour: 610,
    availability: 'Available Now',
    images: [],
    rating: 4.8, reviews: 167, ratingCount: 167,
    features: ['Vineyard Compatible', 'Orchard Use', '55 HP', 'Power Steering'],
    description: 'New Holland 3630 TX Plus — powerful 55 HP tractor with excellent maneuverability for grape orchards.',
  },
  {
    id: 'mr9',
    ownerName: 'Punjab Farm Rentals',
    ownerPhone: '9444001122',
    location: 'Patiala, Punjab',
    equipment: 'Tractor (60 HP)',
    category: 'tractor',
    equipmentHi: 'ट्रैक्टर (60 HP)',
    brand: 'Escorts Farmtrac 60',
    pricePerAcre: 780,
    pricePerHour: 660,
    availability: 'Available Now',
    images: [],
    rating: 4.6, reviews: 95, ratingCount: 95,
    features: ['Deep Tillage', 'Laser Land Levelling', 'Loader Fitted'],
    description: 'Farmtrac 60 with loader attachment. Excellent for land preparation and material handling.',
  },
  {
    id: 'mr10',
    ownerName: 'Kubota Agri Solutions',
    ownerPhone: '9355223344',
    location: 'Hyderabad, Telangana',
    equipment: 'Tractor (55 HP)',
    equipmentHi: 'ट्रैक्टर (55 HP)',
    brand: 'Kubota MU5501',
    pricePerAcre: 740,
    pricePerHour: 630,
    availability: 'Available Now',
    images: [],
    rating: 4.7, reviews: 143, ratingCount: 143,
    features: ['Wet Land Suitable', 'Paddy Field', 'Low Ground Pressure'],
    description: 'Kubota MU5501, perfect for wet paddy fields. Japanese technology, low fuel consumption.',
  },
  {
    id: 'mr11',
    ownerName: 'Mini Farm Mechanisation',
    ownerPhone: '9266334455',
    location: 'Shimla, Himachal Pradesh',
    equipment: 'Mini Tractor (25 HP)',
    category: 'tractor',
    equipmentHi: 'मिनी ट्रैक्टर (25 HP)',
    brand: 'Force Orchard 25',
    pricePerAcre: 380,
    pricePerHour: 320,
    availability: 'Available Now',
    images: [],
    rating: 4.4, reviews: 72, ratingCount: 72,
    features: ['Hill Terrain', 'Orchard Spraying', 'Compact Size', 'Narrow Track'],
    description: 'Force Orchard 25 — compact 25 HP tractor for hilly terrain, apple orchards and small farms.',
  },
  {
    id: 'mr12',
    ownerName: 'Rajasthan Farm Services',
    ownerPhone: '9177445566',
    location: 'Jaipur, Rajasthan',
    equipment: 'Tractor (35 HP)',
    category: 'tractor',
    equipmentHi: 'ट्रैक्टर (35 HP)',
    brand: 'Massey Ferguson 1035',
    pricePerAcre: 500,
    pricePerHour: 420,
    availability: 'Available Now',
    images: [],
    rating: 4.5, reviews: 118, ratingCount: 118,
    features: ['Ploughing', 'Tilling', 'Groundnut Digger', 'Seed Drill'],
    description: 'Classic Massey Ferguson 1035, reliable 35 HP tractor. Economical and easy to maintain.',
  },
  {
    id: 'mr13',
    ownerName: 'Eicher Farm Rentals',
    ownerPhone: '9088556677',
    location: 'Bhopal, Madhya Pradesh',
    equipment: 'Tractor (38 HP)',
    category: 'tractor',
    equipmentHi: 'ट्रैक्टर (38 HP)',
    brand: 'Eicher 380',
    pricePerAcre: 520,
    pricePerHour: 440,
    availability: 'Available from Nov 1',
    images: [],
    rating: 4.3, reviews: 61, ratingCount: 61,
    features: ['Soybean Harvesting Support', 'Ploughing', 'Tilling'],
    description: 'Eicher 380 — fuel efficient 38 HP tractor. Good for central India soybean and wheat belt.',
  },
  // Harvesters
  {
    id: 'mr14',
    ownerName: 'Claas Demo Farm',
    ownerPhone: '9900778899',
    location: 'Karnal, Haryana',
    equipment: 'Rice Harvester',
    category: 'harvester',
    equipmentHi: 'चावल हार्वेस्टर',
    brand: 'Claas Crop Tiger 30 Terra',
    pricePerAcre: 1500,
    pricePerHour: 2000,
    availability: 'Available Oct–Nov',
    images: [],
    rating: 4.9, reviews: 145, ratingCount: 145,
    features: ['Paddy Harvesting', 'Minimum Grain Loss', 'Wet Field Capable'],
    description: 'Claas Crop Tiger 30 Terra — compact rice combine harvester, ideal for small paddy fields.',
  },
  {
    id: 'mr15',
    ownerName: 'Kubota Service Center',
    ownerPhone: '9811889900',
    location: 'Warangal, Telangana',
    equipment: 'Rice/Wheat Harvester',
    category: 'harvester',
    equipmentHi: 'धान/गेहूं हार्वेस्टर',
    brand: 'Kubota DC-68 G',
    pricePerAcre: 1600,
    pricePerHour: 2200,
    availability: 'Available Now',
    images: [],
    rating: 4.8, reviews: 113, ratingCount: 113,
    features: ['Rice & Wheat', 'Low Grain Loss', 'Side Delivery'],
    description: 'Kubota DC-68 G self-propelled combine. Versatile for both paddy and wheat harvesting.',
  },
  {
    id: 'mr16',
    ownerName: 'Modern Agri Solutions',
    ownerPhone: '9722990011',
    location: 'Indore, Madhya Pradesh',
    equipment: 'Multi-Crop Harvester',
    category: 'harvester',
    equipmentHi: 'मल्टी-क्रॉप हार्वेस्टर',
    brand: 'Kartar 4000',
    pricePerAcre: 1700,
    pricePerHour: 2300,
    availability: 'Available Now',
    images: [],
    rating: 4.7, reviews: 98, ratingCount: 98,
    features: ['Wheat', 'Soybean', 'Maize', 'Sunflower', 'Multi-Crop'],
    description: 'Kartar 4000 multi-crop combine harvester. Handles 5+ crops efficiently. Popular in MP belt.',
  },
  {
    id: 'mr17',
    ownerName: 'NH Farm Machinery',
    ownerPhone: '9633001122',
    location: 'Chandigarh, Punjab',
    equipment: 'Wheat Combine Harvester',
    category: 'harvester',
    equipmentHi: 'गेहूं कम्बाइन हार्वेस्टर',
    brand: 'New Holland TC5.30',
    pricePerAcre: 1900,
    pricePerHour: 2600,
    availability: 'Available Mar–Apr',
    images: [],
    rating: 4.8, reviews: 178, ratingCount: 178,
    features: ['Large Capacity', 'Straw Walker', 'GPS Guidance', 'High Speed'],
    description: 'New Holland TC5.30 — high-capacity wheat combine. Up to 8 acres/hour. GPS guided operation.',
  },
  {
    id: 'mr18',
    ownerName: 'Case IH Equipment',
    ownerPhone: '9544112233',
    location: 'Jalgaon, Maharashtra',
    equipment: 'Corn/Wheat Combine',
    category: 'harvester',
    equipmentHi: 'मकई/गेहूं कम्बाइन',
    brand: 'Case IH Axial-Flow 150',
    pricePerAcre: 2200,
    pricePerHour: 3000,
    availability: 'Available on Request',
    images: [],
    rating: 4.9, reviews: 67, ratingCount: 67,
    features: ['Axial Flow Threshing', 'Maize Header', 'Wheat Header', 'Low Losses'],
    description: 'Premium Case IH Axial-Flow combine with interchangeable headers for corn, wheat and soybean.',
  },
  {
    id: 'mr19',
    ownerName: 'Preet Agro Services',
    ownerPhone: '9455223344',
    location: 'Nabha, Punjab',
    equipment: 'Multi-Crop Harvester',
    equipmentHi: 'मल्टी-क्रॉप हार्वेस्टर',
    brand: 'Preet 749',
    pricePerAcre: 1400,
    pricePerHour: 1900,
    availability: 'Available Now',
    images: [],
    rating: 4.5, reviews: 203, ratingCount: 203,
    features: ['Paddy', 'Wheat', 'Multi-Crop', 'Self-Propelled'],
    description: 'Made-in-India Preet 749 self-propelled combine. Budget-friendly, widely used across Punjab.',
  },
  {
    id: 'mr20',
    ownerName: 'Dasmesh Services',
    ownerPhone: '9366334455',
    location: 'Moga, Punjab',
    equipment: 'Paddy/Wheat Harvester',
    category: 'harvester',
    equipmentHi: 'धान/गेहूं हार्वेस्टर',
    brand: 'Dasmesh 9100',
    pricePerAcre: 1550,
    pricePerHour: 2100,
    availability: 'Available from Oct 20',
    images: [],
    rating: 4.6, reviews: 142, ratingCount: 142,
    features: ['Paddy & Wheat', 'Low Grain Loss', 'Good After-Sales Service'],
    description: 'Dasmesh 9100 combine — reliable Indian-made harvester. Great service network across Punjab & Haryana.',
  },
  {
    id: 'mr21',
    ownerName: 'AGCO Service Hub',
    ownerPhone: '9277445566',
    location: 'Rajkot, Gujarat',
    equipment: 'Large-Scale Combine',
    category: 'harvester',
    equipmentHi: 'लार्ज-स्केल कम्बाइन',
    brand: 'AGCO Gleaner S67',
    pricePerAcre: 2500,
    pricePerHour: 3500,
    availability: 'Available on Request',
    images: [],
    rating: 4.8, reviews: 52, ratingCount: 52,
    features: ['Large Farm', 'Multi-Crop', 'Precision Harvest', 'Yield Mapping'],
    description: 'High-end AGCO Gleaner S67 with yield mapping and precision agriculture features. Best for 100+ acre farms.',
  },
  {
    id: 'mr22',
    ownerName: 'Vertical Agri Rentals',
    ownerPhone: '9188556677',
    location: 'Kolkata, West Bengal',
    equipment: 'Mini Rice Harvester',
    category: 'harvester',
    equipmentHi: 'मिनी राइस हार्वेस्टर',
    brand: 'Yanmar AW85V',
    pricePerAcre: 1200,
    pricePerHour: 1600,
    availability: 'Available Now',
    images: [],
    rating: 4.6, reviews: 84, ratingCount: 84,
    features: ['Small Fields', 'Wet Paddy', 'Low Ground Pressure', 'Narrow Design'],
    description: 'Yanmar AW85V mini harvester, perfect for small/fragmented paddy fields in eastern India.',
  },
];

// ─── LABOUR MOCK DATA ─────────────────────────────────────────────────────────

export const LABOUR_LISTINGS = [
  {
    id: 'lb1',
    type: 'group',
    groupName: 'Shram Shakti Group',
    leader: 'Santosh Mane',
    phone: '9988776655',
    location: 'Nashik, Maharashtra',
    workers: 15,
    skills: ['Harvesting', 'Weeding', 'Planting', 'Spraying'],
    pricePerDay: 400,
    pricePerHour: 60,
    available: true,
    rating: 4.6, reviews: 210, ratingCount: 210,
    avatar: 'SS',
    image: null,
    description: 'Experienced group of 15 farm workers. Available 7 days a week. Transport arranged.',
  },
  {
    id: 'lb2',
    type: 'individual',
    groupName: null,
    leader: 'Arun Kale',
    phone: '8877665544',
    location: 'Pune, Maharashtra',
    workers: 1,
    skills: ['Tractor Driving', 'Equipment Operation', 'Irrigation'],
    pricePerDay: 600,
    pricePerHour: 80,
    available: true,
    rating: 4.8, reviews: 95, ratingCount: 95,
    avatar: 'AK',
    image: null,
    description: 'Skilled tractor driver with 10 years experience. Expert in all farming equipment.',
  },
  {
    id: 'lb3',
    type: 'group',
    groupName: 'Mahila Sheti Group',
    leader: 'Savita Pawar',
    phone: '7766554433',
    location: 'Satara, Maharashtra',
    workers: 10,
    skills: ['Paddy Transplanting', 'Grape Harvesting', 'Fruit Picking'],
    pricePerDay: 350,
    pricePerHour: 50,
    available: true,
    rating: 4.7, reviews: 155, ratingCount: 155,
    avatar: 'SP',
    image: null,
    description: 'Women workers group specializing in delicate crop handling. Paddy transplanting experts.',
  },
  {
    id: 'lb4',
    type: 'individual',
    groupName: null,
    leader: 'Vijay Patil',
    phone: '6655443322',
    location: 'Ahmednagar, Maharashtra',
    workers: 1,
    skills: ['Pesticide Spraying', 'Drip Irrigation', 'Fertigation'],
    pricePerDay: 700,
    pricePerHour: 100,
    available: false,
    rating: 4.9, reviews: 78, ratingCount: 78,
    avatar: 'VP',
    image: null,
    description: 'Certified pesticide applicator. Expert in drip irrigation installation and fertigation.',
  },
  {
    id: 'lb5',
    type: 'individual',
    groupName: null,
    leader: 'Raju Shinde',
    phone: '9321456780',
    location: 'Kolhapur, Maharashtra',
    workers: 1,
    skills: ['Ploughing', 'Seed Sowing', 'Harvesting'],
    pricePerDay: 450,
    pricePerHour: 65,
    available: true,
    rating: 4.5, reviews: 62, ratingCount: 62,
    avatar: 'RS',
    image: null,
    description: 'Hard-working farm labourer with 8 years experience in kharif and rabi crops.',
  },
  {
    id: 'lb6',
    type: 'group',
    groupName: 'Kisan Sevak Group',
    leader: 'Dnyanoba Jadhav',
    phone: '9876102030',
    location: 'Solapur, Maharashtra',
    workers: 20,
    skills: ['Sugarcane Harvesting', 'Wheat Cutting', 'Loading'],
    pricePerDay: 380,
    pricePerHour: 55,
    available: true,
    rating: 4.4, reviews: 175, ratingCount: 175,
    avatar: 'KS',
    image: null,
    description: 'Large group of 20 skilled workers. Specialise in sugarcane cutting and wheat harvesting.',
  },
  {
    id: 'lb7',
    type: 'individual',
    groupName: null,
    leader: 'Meena Thorat',
    phone: '7890123456',
    location: 'Jalgaon, Maharashtra',
    workers: 1,
    skills: ['Banana Farming', 'Fruit Picking', 'Packing'],
    pricePerDay: 500,
    pricePerHour: 70,
    available: true,
    rating: 4.7, reviews: 88, ratingCount: 88,
    avatar: 'MT',
    image: null,
    description: 'Expert in banana and fruit crops. Experience in post-harvest handling and packing for export.',
  },
  {
    id: 'lb8',
    type: 'group',
    groupName: 'Punjab Harvest Team',
    leader: 'Gurpreet Singh',
    phone: '9876543000',
    location: 'Amritsar, Punjab',
    workers: 25,
    skills: ['Combine Operation', 'Wheat Harvesting', 'Paddy Cutting'],
    pricePerDay: 450,
    pricePerHour: 65,
    available: true,
    rating: 4.8, reviews: 340, ratingCount: 340,
    avatar: 'PH',
    image: null,
    description: 'Experienced 25-member Punjab harvest team. Available pan-India during harvest season.',
  },
];

// ─── CROP DATA ────────────────────────────────────────────────────────────────

export const CROPS = [
  {
    id: 'c1',
    name: 'Wheat',
    nameHi: 'गेहूं',
    icon: '🌾',
    season: 'Rabi (Winter)',
    sowingMonth: 'October - November',
    harvestMonth: 'March - April',
    duration: '120-150 days',
    waterNeeded: 'Medium (5-6 irrigations)',
    idealTemp: '10-25°C',
    soilType: 'Loamy, Well-drained',
    stages: [
      { name: 'Seed Preparation', nameHi: 'बीज तैयारी', day: 0, duration: 7, tip: 'Select certified seeds. Treat with fungicide before sowing.' },
      { name: 'Sowing', nameHi: 'बुआई', day: 7, duration: 7, tip: 'Sow at 5-6 cm depth. Maintain 22 cm row spacing.' },
      { name: 'Germination', nameHi: 'अंकुरण', day: 14, duration: 10, tip: 'Ensure soil moisture. First irrigation at Crown Root Initiation.' },
      { name: 'Tillering', nameHi: 'कंसे फूटना', day: 30, duration: 25, tip: 'Apply urea top dressing. Remove weeds.' },
      { name: 'Jointing & Booting', nameHi: 'जोड़ लगना', day: 60, duration: 30, tip: 'Second irrigation. Watch for rust disease.' },
      { name: 'Heading & Flowering', nameHi: 'बाली आना', day: 90, duration: 15, tip: 'Critical irrigation period. Avoid water stress.' },
      { name: 'Grain Filling', nameHi: 'दाना भरना', day: 105, duration: 20, tip: 'Last irrigation. Watch for aphids.' },
      { name: 'Maturity & Harvest', nameHi: 'पकाई और कटाई', day: 125, duration: 10, tip: 'Harvest when 90% grains are golden. Use combine harvester.' },
    ],
  },
  {
    id: 'c2',
    name: 'Rice / Paddy',
    nameHi: 'धान / चावल',
    icon: '🌾',
    season: 'Kharif (Monsoon)',
    sowingMonth: 'June - July',
    harvestMonth: 'October - November',
    duration: '105-150 days',
    waterNeeded: 'High (Flooded fields)',
    idealTemp: '22-35°C',
    soilType: 'Clay, Heavy soil',
    stages: [
      { name: 'Nursery Preparation', nameHi: 'नर्सरी तैयारी', day: 0, duration: 25, tip: 'Prepare raised nursery beds. 25 days nursery period.' },
      { name: 'Transplanting', nameHi: 'रोपाई', day: 25, duration: 7, tip: 'Transplant 25-day old seedlings. Maintain 4-5 cm water level.' },
      { name: 'Vegetative Growth', nameHi: 'शाकाहारी विकास', day: 35, duration: 40, tip: 'Apply basal fertilizer. Maintain flooded conditions.' },
      { name: 'Tillering', nameHi: 'कंसे', day: 40, duration: 25, tip: 'Apply nitrogen top dressing. Weed management critical.' },
      { name: 'Panicle Initiation', nameHi: 'बाली शुरू', day: 70, duration: 15, tip: 'Drain field briefly for aeration. Watch for blast disease.' },
      { name: 'Heading & Flowering', nameHi: 'फूल आना', day: 85, duration: 15, tip: 'Maintain water level. Critical pollination period.' },
      { name: 'Grain Filling & Maturity', nameHi: 'दाना पकना', day: 100, duration: 20, tip: 'Drain field 2 weeks before harvest. Check grain moisture.' },
      { name: 'Harvest', nameHi: 'कटाई', day: 120, duration: 7, tip: 'Harvest when 85% grains are golden. Thresh immediately.' },
    ],
  },
  {
    id: 'c3',
    name: 'Tomato',
    nameHi: 'टमाटर',
    icon: '🍅',
    season: 'All Year (Rabi preferred)',
    sowingMonth: 'September - October',
    harvestMonth: 'January - March',
    duration: '90-120 days',
    waterNeeded: 'Medium (Drip irrigation best)',
    idealTemp: '18-27°C',
    soilType: 'Sandy Loam, Well-drained',
    stages: [
      { name: 'Nursery', nameHi: 'नर्सरी', day: 0, duration: 25, tip: 'Sow in raised nursery. Use pro-trays for better results.' },
      { name: 'Transplanting', nameHi: 'रोपाई', day: 25, duration: 5, tip: 'Transplant in evening. Water immediately after transplanting.' },
      { name: 'Vegetative Stage', nameHi: 'पत्ता विकास', day: 30, duration: 20, tip: 'Stake plants when 30cm tall. Apply growth promoters.' },
      { name: 'Flowering', nameHi: 'फूल आना', day: 50, duration: 15, tip: 'Ensure potassium supply. Spray boron for fruit setting.' },
      { name: 'Fruit Setting', nameHi: 'फल लगना', day: 65, duration: 15, tip: 'Spray calcium for blossom-end rot prevention.' },
      { name: 'Fruit Development', nameHi: 'फल विकास', day: 80, duration: 20, tip: 'Watch for leaf curl virus. Maintain consistent irrigation.' },
      { name: 'Harvest', nameHi: 'तुड़ाई', day: 100, duration: 30, tip: 'Start harvesting when fruits turn light pink. Multiple pickings.' },
    ],
  },
  {
    id: 'c4',
    name: 'Soybean',
    nameHi: 'सोयाबीन',
    icon: '🫘',
    season: 'Kharif (Monsoon)',
    sowingMonth: 'June - July',
    harvestMonth: 'September - October',
    duration: '90-100 days',
    waterNeeded: 'Medium',
    idealTemp: '20-30°C',
    soilType: 'Well-drained, Loamy',
    stages: [
      { name: 'Seed Treatment', nameHi: 'बीज उपचार', day: 0, duration: 3, tip: 'Treat seeds with Rhizobium culture for nitrogen fixation.' },
      { name: 'Sowing', nameHi: 'बुआई', day: 3, duration: 5, tip: 'Sow at 45cm x 5cm spacing. Depth 3-4 cm. Soil moisture essential.' },
      { name: 'Emergence', nameHi: 'अंकुरण', day: 8, duration: 10, tip: 'Thin overcrowded plants. First weeding at 20 days.' },
      { name: 'Vegetative Growth', nameHi: 'पत्ता विकास', day: 20, duration: 30, tip: 'Apply phosphorus. Spray insecticide for girdle beetle.' },
      { name: 'Flowering', nameHi: 'फूल', day: 40, duration: 15, tip: 'Avoid water stress. Critical period for pod setting.' },
      { name: 'Pod Development', nameHi: 'फली', day: 55, duration: 25, tip: 'Watch for pod borer. Spray recommended insecticide.' },
      { name: 'Maturity & Harvest', nameHi: 'पकाई', day: 90, duration: 7, tip: 'Harvest when 95% pods turn brown. Harvest early morning.' },
    ],
  },
  {
    id: 'c5',
    name: 'Onion',
    nameHi: 'प्याज',
    icon: '🧅',
    season: 'Rabi (Winter)',
    sowingMonth: 'October - November',
    harvestMonth: 'March - April',
    duration: '130-160 days',
    waterNeeded: 'Medium (Drip preferred)',
    idealTemp: '13-24°C',
    soilType: 'Sandy Loam, Rich in Sulfur',
    stages: [
      { name: 'Nursery', nameHi: 'नर्सरी', day: 0, duration: 40, tip: 'Sow densely in raised beds. 40-day nursery period.' },
      { name: 'Field Preparation & Transplanting', nameHi: 'रोपाई', day: 40, duration: 7, tip: 'Transplant at 10x10 cm spacing. Avoid deep planting.' },
      { name: 'Vegetative Growth', nameHi: 'पत्ता विकास', day: 50, duration: 40, tip: 'Weed twice. Apply nitrogen for leaf growth.' },
      { name: 'Bulb Formation', nameHi: 'प्याज बनना', day: 90, duration: 40, tip: 'Stop nitrogen. Apply potash and phosphorus for bulb quality.' },
      { name: 'Maturity', nameHi: 'पकाई', day: 130, duration: 15, tip: 'Reduce irrigation 15 days before harvest. Tops will fall.' },
      { name: 'Harvest & Curing', nameHi: 'खुदाई', day: 145, duration: 10, tip: 'Harvest when 50% tops fall. Cure in shade for 7-10 days.' },
    ],
  },
];

// ─── WEATHER FORECAST MOCK DATA ───────────────────────────────────────────────
// Not imported anywhere — kept only for local Postman/dev reference.

export const WEATHER_MOCK = {
  city: 'Nashik',
  state: 'Maharashtra',
  current: {
    temp: 28,
    feelsLike: 31,
    humidity: 65,
    windSpeed: 12,
    windDir: 'SW',
    condition: 'Partly Cloudy',
    icon: 'partly-sunny',
    uvIndex: 6,
    visibility: 8,
    pressure: 1012,
    rainChance: 30,
  },
  hourly: [
    { time: '6 AM', temp: 22, icon: 'sunny', rain: 0 },
    { time: '9 AM', temp: 26, icon: 'partly-sunny', rain: 5 },
    { time: '12 PM', temp: 31, icon: 'partly-sunny', rain: 20 },
    { time: '3 PM', temp: 33, icon: 'cloud', rain: 40 },
    { time: '6 PM', temp: 29, icon: 'rainy', rain: 70 },
    { time: '9 PM', temp: 25, icon: 'rainy', rain: 60 },
  ],
  weekly: [
    { day: 'Mon', high: 33, low: 22, icon: 'partly-sunny', rain: 20 },
    { day: 'Tue', high: 31, low: 21, icon: 'rainy', rain: 70 },
    { day: 'Wed', high: 28, low: 20, icon: 'rainy', rain: 80 },
    { day: 'Thu', high: 30, low: 21, icon: 'partly-sunny', rain: 30 },
    { day: 'Fri', high: 34, low: 23, icon: 'sunny', rain: 10 },
    { day: 'Sat', high: 35, low: 24, icon: 'sunny', rain: 5 },
    { day: 'Sun', high: 33, low: 22, icon: 'partly-sunny', rain: 15 },
  ],
  alerts: [
    {
      type: 'warning',
      title: 'Rain Alert',
      message: 'Heavy rain expected Tuesday-Wednesday. Delay pesticide spraying.',
      icon: 'rainy',
    },
  ],
  farmingTip: 'Good time to apply basal fertilizer. Irrigate fields before expected rain.',
};

// ─── CHAT MESSAGES MOCK ───────────────────────────────────────────────────────

export const MOCK_MESSAGES = [
  {
    id: 'm1',
    senderId: 'other',
    senderName: 'Ramesh Kumar',
    text: 'Namaskar! Aapko meri Gir gaay mein interest hai?',
    time: '10:30 AM',
    date: 'Today',
  },
  {
    id: 'm2',
    senderId: 'me',
    text: 'Haan, kya gaay ki health theek hai? Milk yield kaisi hai?',
    time: '10:32 AM',
    date: 'Today',
  },
  {
    id: 'm3',
    senderId: 'other',
    senderName: 'Ramesh Kumar',
    text: 'Bilkul theek hai. Daily 12 litre milk deti hai. Doctor certificate bhi hai.',
    time: '10:35 AM',
    date: 'Today',
  },
];

// ─── COMMUNITY POSTS MOCK DATA ────────────────────────────────────────────────

export const POST_CATEGORIES = [
  { id: 'all',     label: 'All',           icon: 'apps',             color: '#1B4332' },
  { id: 'problem', label: 'Crop Problem',  icon: 'bug',              color: '#E63946' },
  { id: 'tip',     label: 'Farming Tips',  icon: 'bulb',             color: '#FFB703' },
  { id: 'market',  label: 'Market Price',  icon: 'trending-up',      color: '#4CC9F0' },
  { id: 'success', label: 'Success Story', icon: 'ribbon',           color: '#52B788' },
  { id: 'weather', label: 'Weather Talk',  icon: 'partly-sunny',     color: '#F4A261' },
  { id: 'general', label: 'General',       icon: 'chatbubbles',      color: '#7F9B87' },
];

export const COMMUNITY_POSTS = [
  {
    id: 'post1',
    authorName: 'Ramesh Patil',
    authorAvatar: 'RP',
    authorLocation: 'Nashik, Maharashtra',
    authorCrop: 'Tomato, Onion',
    category: 'problem',
    title: 'Tomato leaves turning yellow from bottom – urgent help!',
    description: 'My tomato plants are 45 days old. Leaves are turning yellow from the bottom and spreading up. Some plants are wilting too. Soil is black cotton. What disease is this and what spray should I use?',
    image: null,
    likes: 38,
    comments: 12,
    liked: false,
    bookmarked: false,
    timeAgo: '2 hours ago',
    tags: ['Tomato', 'Yellow Leaves', 'Disease'],
    verified: false,
  },
  {
    id: 'post2',
    authorName: 'Dr. Suresh KVK',
    authorAvatar: 'SK',
    authorLocation: 'Pune KVK, Maharashtra',
    authorCrop: 'Agriculture Expert',
    category: 'tip',
    title: 'Best time to apply DAP fertilizer for wheat – must read!',
    description: 'Farmers, apply DAP only as basal dose at time of sowing. Many farmers apply it as top dressing which is wasteful. DAP must be mixed in soil for roots to absorb phosphorus properly. Top dressing with Urea is correct after 21 days.',
    image: null,
    likes: 124,
    comments: 34,
    liked: true,
    bookmarked: true,
    timeAgo: '5 hours ago',
    tags: ['Wheat', 'DAP', 'Fertilizer Tip'],
    verified: true,
  },
  {
    id: 'post3',
    authorName: 'Mohan Yadav',
    authorAvatar: 'MY',
    authorLocation: 'Indore, MP',
    authorCrop: 'Soybean, Wheat',
    category: 'market',
    title: 'Soybean price update – Indore mandi today ₹4,850/quintal',
    description: 'Today at Indore mandi: Soybean ₹4,850/quintal. Last week it was ₹4,600. Experts say prices may go up to ₹5,200 by December due to low production this kharif. Hold stock if you can wait 3-4 weeks.',
    image: null,
    likes: 89,
    comments: 45,
    liked: false,
    bookmarked: false,
    timeAgo: '8 hours ago',
    tags: ['Soybean', 'Mandi Price', 'Market Update'],
    verified: false,
  },
  {
    id: 'post4',
    authorName: 'Savita Devi',
    authorAvatar: 'SD',
    authorLocation: 'Varanasi, UP',
    authorCrop: 'Rice, Vegetable',
    category: 'success',
    title: 'Started drip irrigation – saved 60% water and doubled income!',
    description: 'Two years ago I took government subsidy for drip irrigation on my 2 acre field. Before, I used to flood irrigate and water bill was ₹8,000/month. Now with drip, it is only ₹3,000. Also my vegetable yield doubled because plants get water exactly when needed. Other farmers should try this!',
    image: null,
    likes: 215,
    comments: 67,
    liked: true,
    bookmarked: false,
    timeAgo: '1 day ago',
    tags: ['Drip Irrigation', 'Success Story', 'Water Saving'],
    verified: false,
  },
  {
    id: 'post5',
    authorName: 'Bharat Singh',
    authorAvatar: 'BS',
    authorLocation: 'Amritsar, Punjab',
    authorCrop: 'Wheat, Paddy',
    category: 'problem',
    title: 'White powder on wheat leaves – is this powdery mildew?',
    description: 'White powder like coating on wheat leaves. Started on lower leaves, now spreading to upper leaves also. Temperature here is around 18-22°C with morning fog. Is this powdery mildew? Which fungicide should I use and how many times?',
    image: null,
    likes: 19,
    comments: 9,
    liked: false,
    bookmarked: false,
    timeAgo: '1 day ago',
    tags: ['Wheat', 'Powdery Mildew', 'Fungal Disease'],
    verified: false,
  },
  {
    id: 'post6',
    authorName: 'Agri Expert - KVK',
    authorAvatar: 'AE',
    authorLocation: 'Coimbatore, Tamil Nadu',
    authorCrop: 'Agriculture Scientist',
    category: 'tip',
    title: 'How to do soil testing at home before spending on fertilizers',
    description: 'Before buying fertilizers, always do soil test. You can get soil testing kit from nearest KVK (Krishi Vigyan Kendra) for just ₹5-10. Or take soil sample to agriculture department lab free of cost. This will tell exact nutrient deficiency and save you ₹3,000-5,000 per acre on unnecessary fertilizers.',
    image: null,
    likes: 342,
    comments: 89,
    liked: false,
    bookmarked: true,
    timeAgo: '2 days ago',
    tags: ['Soil Testing', 'Money Saving', 'Expert Advice'],
    verified: true,
  },
];

export const COMMUNITY_COMMENTS = {
  post1: [
    { id: 'c1', authorName: 'Vijay Patil', authorAvatar: 'VP', text: 'This looks like Early Blight (Alternaria). Spray Mancozeb 75% WP at 2.5g per litre water. Repeat after 10 days.', timeAgo: '1 hour ago', likes: 15 },
    { id: 'c2', authorName: 'Dr. KVK Expert', authorAvatar: 'DE', text: 'Also check for Fusarium wilt if plants are dying completely. Pull out affected plants and destroy them immediately before it spreads.', timeAgo: '45 min ago', likes: 22 },
    { id: 'c3', authorName: 'Santosh Mane', authorAvatar: 'SM', text: 'Same problem I had last year. Copper oxychloride spray worked very well for me. 3 sprays every 10 days.', timeAgo: '30 min ago', likes: 8 },
  ],
  post2: [
    { id: 'c4', authorName: 'Dinesh Kumar', authorAvatar: 'DK', text: 'Thank you sir! I was applying DAP as top dressing for 5 years. Now I understand my mistake. Will change this season.', timeAgo: '4 hours ago', likes: 31 },
    { id: 'c5', authorName: 'Meena Devi', authorAvatar: 'MD', text: 'What about MOP? Should it also be given at basal only?', timeAgo: '3 hours ago', likes: 7 },
  ],
};

// ─── USER PROFILE MOCK DATA ──────────────────────────────────────────────────

export const USER_PROFILE = {
  id: 'user1',
  name: 'Shubham Yeljale',
  phone: '+91 98765 43210',
  village: 'Shirdi',
  district: 'Ahmednagar',
  state: 'Maharashtra',
  pincode: '423414',
  avatar: 'SY',
  memberSince: 'January 2024',
  verified: true,
  farm: {
    totalLand: '4.5 acres',
    landType: 'Black Cotton Soil',
    irrigationType: 'Drip + Borewell',
    mainCrops: ['Tomato', 'Onion', 'Wheat'],
    animals: ['2 Cows', '1 Buffalo'],
    village: 'Shirdi, Ahmednagar',
  },
  stats: {
    posts: 12,
    questions: 8,
    helpful: 34,
    listings: 3,
  },
  myPosts: ['post4'],
  savedPosts: ['post2', 'post6'],
};
