/**
 * Seed veterinary doctors for development/testing.
 * Run: node prisma/seed-vets.js
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const DOCTORS = [
  {
    fullNameEn: 'Dr. Ramesh Patil',
    fullNameMr: 'डॉ. रमेश पाटील',
    phone: '+919876543210',
    gender: 'male',
    dateOfBirth: new Date('1988-03-15'),
    profilePhoto: null,
    village: 'बारामती',
    taluka: 'बारामती',
    district: 'Pune',
    state: 'Maharashtra',
    pincode: '413102',
    latitude: 18.1555,
    longitude: 74.5815,
    registrationNumber: 'MSVC/2015/1234',
    councilName: 'Maharashtra State Veterinary Council',
    experienceYears: 12,
    qualifications: [
      { degree: 'BVSc', college: 'Bombay Veterinary College', university: 'MAFSU, Nagpur', yearOfPassing: 2010 },
      { degree: 'MVSc', specialization: 'Animal Surgery', college: 'BVC', university: 'MAFSU', yearOfPassing: 2013 },
    ],
    practiceType: 'both',
    clinicName: 'Patil Veterinary Clinic',
    clinicAddress: 'दुकान क्र. 5, बस स्टँडजवळ, बारामती',
    clinicPhotos: [],
    animalTypes: ['cow', 'buffalo', 'goat', 'poultry'],
    services: ['general_checkup', 'vaccination', 'artificial_insemination', 'surgery', 'pregnancy_diagnosis', 'emergency'],
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat'],
    startTime: '09:00',
    endTime: '18:00',
    emergencyAvailable: true,
    consultationFee: 200,
    visitFee: 500,
    feeNoteEn: 'Fee may vary by animal size',
    feeNoteMr: 'शुल्क प्राण्यांच्या आकारानुसार बदलतो',
    languages: ['marathi', 'hindi'],
    verificationStatus: 'verified',
    isActive: true,
    isListed: true,
    ratingAverage: 4.5,
    ratingCount: 23,
    priority: 10,
  },
  {
    fullNameEn: 'Dr. Sunita Jadhav',
    fullNameMr: 'डॉ. सुनिता जाधव',
    phone: '+919876543211',
    gender: 'female',
    profilePhoto: null,
    village: 'इंदापूर',
    taluka: 'इंदापूर',
    district: 'Pune',
    state: 'Maharashtra',
    pincode: '413106',
    latitude: 18.1080,
    longitude: 75.0239,
    registrationNumber: 'MSVC/2018/5678',
    councilName: 'Maharashtra State Veterinary Council',
    experienceYears: 8,
    qualifications: [
      { degree: 'BVSc_AH', college: 'KNP College of Veterinary Science', university: 'MAFSU', yearOfPassing: 2016 },
    ],
    practiceType: 'mobile',
    clinicPhotos: [],
    animalTypes: ['cow', 'buffalo', 'goat'],
    services: ['general_checkup', 'vaccination', 'deworming', 'farm_visit', 'feed_nutrition_advice'],
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri'],
    startTime: '08:00',
    endTime: '17:00',
    emergencyAvailable: false,
    consultationFee: 150,
    visitFee: 400,
    languages: ['marathi', 'hindi', 'english'],
    verificationStatus: 'verified',
    isActive: true,
    isListed: true,
    ratingAverage: 4.8,
    ratingCount: 45,
    priority: 8,
  },
  {
    fullNameEn: 'Dr. Vikas Deshmukh',
    fullNameMr: 'डॉ. विकास देशमुख',
    phone: '+919876543212',
    gender: 'male',
    profilePhoto: null,
    village: 'सातारा',
    taluka: 'सातारा',
    district: 'Satara',
    state: 'Maharashtra',
    pincode: '415001',
    latitude: 17.6805,
    longitude: 74.0183,
    registrationNumber: 'MSVC/2012/9012',
    councilName: 'Maharashtra State Veterinary Council',
    experienceYears: 16,
    qualifications: [
      { degree: 'BVSc', college: 'Nagpur Veterinary College', university: 'MAFSU', yearOfPassing: 2008 },
      { degree: 'PhD', specialization: 'Veterinary Medicine', college: 'NVC', university: 'MAFSU', yearOfPassing: 2018 },
    ],
    practiceType: 'clinic',
    clinicName: 'Deshmukh Animal Hospital',
    clinicAddress: 'Main Road, Satara',
    clinicPhotos: [],
    animalTypes: ['cow', 'buffalo', 'goat', 'sheep', 'horse', 'dog', 'cat'],
    services: ['general_checkup', 'vaccination', 'surgery', 'emergency', 'skin_treatment', 'mastitis_treatment', 'infertility_treatment'],
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
    startTime: '08:00',
    endTime: '20:00',
    emergencyAvailable: true,
    consultationFee: 300,
    visitFee: 800,
    languages: ['marathi', 'hindi', 'english'],
    verificationStatus: 'verified',
    isActive: true,
    isListed: true,
    ratingAverage: 4.8,
    ratingCount: 67,
    priority: 15,
  },
  {
    fullNameEn: 'Dr. Priya Kulkarni',
    fullNameMr: 'डॉ. प्रिया कुलकर्णी',
    phone: '+919876543213',
    gender: 'female',
    profilePhoto: null,
    village: 'कोल्हापूर',
    taluka: 'कोल्हापूर',
    district: 'Kolhapur',
    state: 'Maharashtra',
    pincode: '416001',
    latitude: 16.7050,
    longitude: 74.2433,
    registrationNumber: 'MSVC/2020/3344',
    councilName: 'Maharashtra State Veterinary Council',
    experienceYears: 4,
    qualifications: [
      { degree: 'BVSc_AH', college: 'Bombay Veterinary College', university: 'MAFSU', yearOfPassing: 2020 },
    ],
    practiceType: 'mobile',
    clinicPhotos: [],
    animalTypes: ['cow', 'buffalo', 'goat', 'sheep', 'poultry'],
    services: ['general_checkup', 'vaccination', 'deworming', 'artificial_insemination', 'pregnancy_diagnosis', 'farm_visit', 'telemedicine'],
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat'],
    startTime: '09:00',
    endTime: '17:00',
    emergencyAvailable: false,
    consultationFee: 100,
    visitFee: 350,
    feeNoteEn: 'Telemedicine consultation free for first visit',
    feeNoteMr: 'पहिल्या भेटीसाठी दूरस्थ सल्ला विनामूल्य',
    languages: ['marathi', 'hindi', 'english', 'kannada'],
    verificationStatus: 'verified',
    isActive: true,
    isListed: true,
    ratingAverage: 4.3,
    ratingCount: 12,
    priority: 5,
  },
  {
    fullNameEn: 'Dr. Suresh More',
    fullNameMr: 'डॉ. सुरेश मोरे',
    phone: '+919876543214',
    gender: 'male',
    profilePhoto: null,
    village: 'नाशिक',
    taluka: 'नाशिक',
    district: 'Nashik',
    state: 'Maharashtra',
    pincode: '422001',
    latitude: 19.9975,
    longitude: 73.7898,
    registrationNumber: 'MSVC/2010/7788',
    councilName: 'Maharashtra State Veterinary Council',
    experienceYears: 20,
    qualifications: [
      { degree: 'BVSc', college: 'Nagpur Veterinary College', university: 'MAFSU', yearOfPassing: 2004 },
      { degree: 'MVSc', specialization: 'Gynaecology', college: 'NVC', university: 'MAFSU', yearOfPassing: 2007 },
    ],
    practiceType: 'both',
    clinicName: 'More Pashuvaidyak Clinic',
    clinicAddress: 'College Road, Nashik',
    clinicPhotos: [],
    animalTypes: ['cow', 'buffalo', 'goat', 'sheep', 'pig'],
    services: ['general_checkup', 'vaccination', 'artificial_insemination', 'pregnancy_diagnosis', 'infertility_treatment', 'emergency', 'postmortem', 'farm_visit'],
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat'],
    startTime: '08:30',
    endTime: '19:00',
    emergencyAvailable: true,
    consultationFee: 250,
    visitFee: 600,
    languages: ['marathi', 'hindi'],
    verificationStatus: 'verified',
    isActive: true,
    isListed: true,
    ratingAverage: 4.6,
    ratingCount: 38,
    priority: 12,
  },
  {
    fullNameEn: 'Dr. Anil Bhosale',
    fullNameMr: 'डॉ. अनिल भोसले',
    phone: '+919876543215',
    gender: 'male',
    profilePhoto: null,
    village: 'सोलापूर',
    taluka: 'सोलापूर',
    district: 'Solapur',
    state: 'Maharashtra',
    pincode: '413001',
    latitude: 17.6868,
    longitude: 75.9064,
    registrationNumber: 'MSVC/2014/4455',
    councilName: 'Maharashtra State Veterinary Council',
    experienceYears: 10,
    qualifications: [
      { degree: 'BVSc', college: 'KNP College of Veterinary Science', university: 'MAFSU', yearOfPassing: 2014 },
      { degree: 'MVSc', specialization: 'Poultry Science', college: 'KNP', university: 'MAFSU', yearOfPassing: 2017 },
    ],
    practiceType: 'both',
    clinicName: 'Bhosale Pashu Clinic',
    clinicAddress: 'Station Road, Solapur',
    clinicPhotos: [],
    animalTypes: ['cow', 'buffalo', 'goat', 'poultry', 'sheep'],
    services: ['general_checkup', 'vaccination', 'deworming', 'emergency', 'farm_visit', 'feed_nutrition_advice'],
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat'],
    startTime: '08:00',
    endTime: '18:30',
    emergencyAvailable: true,
    consultationFee: 180,
    visitFee: 450,
    feeNoteEn: 'Home visits available within 15 km radius',
    feeNoteMr: '15 किमी परिसरात घरभेट उपलब्ध',
    languages: ['marathi', 'hindi', 'kannada'],
    verificationStatus: 'verified',
    isActive: true,
    isListed: true,
    ratingAverage: 4.4,
    ratingCount: 18,
    priority: 7,
  },
  {
    fullNameEn: 'Dr. Meena Gaikwad',
    fullNameMr: 'डॉ. मीना गायकवाड',
    phone: '+919876543216',
    gender: 'female',
    profilePhoto: null,
    village: 'औरंगाबाद',
    taluka: 'औरंगाबाद',
    district: 'Aurangabad',
    state: 'Maharashtra',
    pincode: '431001',
    latitude: 19.8762,
    longitude: 75.3433,
    registrationNumber: 'MSVC/2016/6677',
    councilName: 'Maharashtra State Veterinary Council',
    experienceYears: 7,
    qualifications: [
      { degree: 'BVSc_AH', college: 'Bombay Veterinary College', university: 'MAFSU', yearOfPassing: 2017 },
    ],
    practiceType: 'mobile',
    clinicPhotos: [],
    animalTypes: ['cow', 'buffalo', 'goat', 'sheep', 'dog', 'cat'],
    services: ['general_checkup', 'vaccination', 'deworming', 'skin_treatment', 'farm_visit', 'telemedicine'],
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
    startTime: '07:30',
    endTime: '16:00',
    emergencyAvailable: false,
    consultationFee: 120,
    visitFee: 320,
    feeNoteEn: 'Free first telemedicine consultation',
    feeNoteMr: 'पहिला दूरस्थ सल्ला विनामूल्य',
    languages: ['marathi', 'hindi', 'english'],
    verificationStatus: 'verified',
    isActive: true,
    isListed: true,
    ratingAverage: 4.7,
    ratingCount: 29,
    priority: 9,
  },
  {
    fullNameEn: 'Dr. Santosh Kamble',
    fullNameMr: 'डॉ. संतोष कांबळे',
    phone: '+919876543217',
    gender: 'male',
    profilePhoto: null,
    village: 'लातूर',
    taluka: 'लातूर',
    district: 'Latur',
    state: 'Maharashtra',
    pincode: '413512',
    latitude: 18.4088,
    longitude: 76.5604,
    registrationNumber: 'MSVC/2009/2233',
    councilName: 'Maharashtra State Veterinary Council',
    experienceYears: 15,
    qualifications: [
      { degree: 'BVSc', college: 'Nagpur Veterinary College', university: 'MAFSU', yearOfPassing: 2009 },
      { degree: 'MVSc', specialization: 'Animal Reproduction', college: 'NVC', university: 'MAFSU', yearOfPassing: 2012 },
    ],
    practiceType: 'clinic',
    clinicName: 'Kamble Animal Care Centre',
    clinicAddress: 'Main Bazaar, Latur',
    clinicPhotos: [],
    animalTypes: ['cow', 'buffalo', 'goat', 'sheep', 'horse'],
    services: ['general_checkup', 'vaccination', 'artificial_insemination', 'pregnancy_diagnosis', 'infertility_treatment', 'emergency', 'postmortem'],
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat'],
    startTime: '09:00',
    endTime: '19:00',
    emergencyAvailable: true,
    consultationFee: 220,
    visitFee: 550,
    languages: ['marathi', 'hindi', 'english'],
    verificationStatus: 'verified',
    isActive: true,
    isListed: true,
    ratingAverage: 4.9,
    ratingCount: 52,
    priority: 14,
  },
  {
    fullNameEn: 'Dr. Rohini Shinde',
    fullNameMr: 'डॉ. रोहिणी शिंदे',
    phone: '+919876543218',
    gender: 'female',
    profilePhoto: null,
    village: 'अमरावती',
    taluka: 'अमरावती',
    district: 'Amravati',
    state: 'Maharashtra',
    pincode: '444601',
    latitude: 20.9374,
    longitude: 77.7796,
    registrationNumber: 'MSVC/2019/8899',
    councilName: 'Maharashtra State Veterinary Council',
    experienceYears: 5,
    qualifications: [
      { degree: 'BVSc_AH', college: 'KNP College of Veterinary Science', university: 'MAFSU', yearOfPassing: 2019 },
    ],
    practiceType: 'mobile',
    clinicPhotos: [],
    animalTypes: ['cow', 'buffalo', 'goat', 'poultry', 'rabbit', 'fish'],
    services: ['general_checkup', 'vaccination', 'deworming', 'farm_visit', 'feed_nutrition_advice', 'telemedicine'],
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri'],
    startTime: '10:00',
    endTime: '17:00',
    emergencyAvailable: false,
    consultationFee: 100,
    visitFee: 300,
    feeNoteEn: 'Specialises in poultry and small animals',
    feeNoteMr: 'कुक्कुट व लहान प्राण्यांमध्ये तज्ञ',
    languages: ['marathi', 'hindi'],
    verificationStatus: 'verified',
    isActive: true,
    isListed: true,
    ratingAverage: 4.2,
    ratingCount: 8,
    priority: 4,
  },
  {
    fullNameEn: 'Dr. Ganesh Pawar',
    fullNameMr: 'डॉ. गणेश पवार',
    phone: '+919876543219',
    gender: 'male',
    profilePhoto: null,
    village: 'जळगाव',
    taluka: 'जळगाव',
    district: 'Jalgaon',
    state: 'Maharashtra',
    pincode: '425001',
    latitude: 21.0077,
    longitude: 75.5626,
    registrationNumber: 'MSVC/2006/1122',
    councilName: 'Maharashtra State Veterinary Council',
    experienceYears: 18,
    qualifications: [
      { degree: 'BVSc', college: 'Bombay Veterinary College', university: 'MAFSU', yearOfPassing: 2006 },
      { degree: 'MVSc', specialization: 'Animal Medicine', college: 'BVC', university: 'MAFSU', yearOfPassing: 2009 },
      { degree: 'PhD', specialization: 'Livestock Disease Management', college: 'BVC', university: 'MAFSU', yearOfPassing: 2016 },
    ],
    practiceType: 'both',
    clinicName: 'Pawar Veterinary & Research Clinic',
    clinicAddress: 'College Road, Jalgaon',
    clinicPhotos: [],
    animalTypes: ['cow', 'buffalo', 'goat', 'sheep', 'horse', 'camel', 'pig'],
    services: ['general_checkup', 'vaccination', 'surgery', 'emergency', 'mastitis_treatment', 'infertility_treatment', 'artificial_insemination', 'pregnancy_diagnosis', 'postmortem', 'farm_visit'],
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
    startTime: '07:00',
    endTime: '21:00',
    emergencyAvailable: true,
    consultationFee: 350,
    visitFee: 900,
    feeNoteEn: 'Senior specialist — fee may vary for complex cases',
    feeNoteMr: 'वरिष्ठ तज्ञ — जटिल प्रकरणांसाठी शुल्क बदलू शकते',
    languages: ['marathi', 'hindi', 'english', 'gujarati'],
    verificationStatus: 'verified',
    isActive: true,
    isListed: true,
    ratingAverage: 5.0,
    ratingCount: 91,
    priority: 20,
  },
];

async function main() {
  console.log('Seeding veterinary doctors...');
  let created = 0;
  let skipped = 0;

  for (const doc of DOCTORS) {
    const existing = await prisma.veterinaryDoctor.findUnique({
      where: { phone: doc.phone },
    });

    if (existing) {
      await prisma.veterinaryDoctor.update({ where: { phone: doc.phone }, data: doc });
      skipped++;
    } else {
      await prisma.veterinaryDoctor.create({ data: doc });
      created++;
    }
  }

  console.log(`Done: ${created} created, ${skipped} updated.`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
