/**
 * Seed government schemes — run once:
 *   node prisma/seed-schemes.js
 */
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const SCHEMES = [
  {
    schemeCode: 'PM_KISAN',
    schemeName: 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
    schemeNameHi: 'प्रधानमंत्री किसान सम्मान निधि',
    schemeNameMr: 'पंतप्रधान किसान सन्मान निधी',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    type: 'central',
    state: null,
    description: 'Direct income support of ₹6,000 per year to small and marginal farmer families having combined land holding up to 2 hectares. Amount is paid in three equal installments of ₹2,000 every four months directly to farmer bank accounts.',
    benefitsSummary: '₹6,000/year direct cash in 3 installments to farmer bank account',
    eligibility: { landSizeMaxAcres: 4.94, casteCategories: ['general','obc','sc','st'], incomeLimit: null, ageMin: 18, ageMax: null, farmingTypes: ['any'] },
    documentsReq: ['Aadhaar card', 'Bank passbook', 'Land records (7/12)', 'Mobile number'],
    applicationUrl: 'https://pmkisan.gov.in',
    helpline: '155261 / 011-23381092',
    benefitAmount: 6000,
    benefitType: 'cash',
    deadline: null,
    isActive: true,
    fullText: 'PM-KISAN provides income support of Rs 6000 per year to all landholding farmer families across the country in three equal installments of Rs 2000 each every four months. The scheme covers farmer families having combined land holding upto 2 hectares. Registration is done through local Patwari/Revenue officer or Common Service Centres.',
  },
  {
    schemeCode: 'PMFBY',
    schemeName: 'PMFBY (Pradhan Mantri Fasal Bima Yojana)',
    schemeNameHi: 'प्रधानमंत्री फसल बीमा योजना',
    schemeNameMr: 'पंतप्रधान पीक विमा योजना',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    type: 'central',
    state: null,
    description: 'Comprehensive crop insurance scheme. Covers crop failure due to natural calamities, pests, diseases. Premium is heavily subsidised — farmer pays only 2% for Kharif crops, 1.5% for Rabi, and 5% for commercial/horticultural crops.',
    benefitsSummary: 'Crop failure insurance — farmer pays only 1.5-5% premium, rest paid by govt',
    eligibility: { landSizeMaxAcres: null, casteCategories: ['general','obc','sc','st'], incomeLimit: null, ageMin: 18, ageMax: null, farmingTypes: ['any'] },
    documentsReq: ['Aadhaar card', 'Bank passbook', 'Land records', 'Sowing certificate', 'Loan passbook (if KCC holder)'],
    applicationUrl: 'https://pmfby.gov.in',
    helpline: '1800-180-1551',
    benefitAmount: null,
    benefitType: 'insurance',
    deadline: 'Before sowing of each crop season',
    isActive: true,
    fullText: 'PMFBY covers all food and oilseed crops and annual commercial and horticultural crops for which past yield data is available. Risks covered: natural calamities, pests, diseases, prevented sowing, post-harvest losses. Compulsory for loanee farmers; voluntary for non-loanee farmers.',
  },
  {
    schemeCode: 'KCC',
    schemeName: 'KCC (Kisan Credit Card)',
    schemeNameHi: 'किसान क्रेडिट कार्ड',
    schemeNameMr: 'किसान क्रेडिट कार्ड',
    ministry: 'Ministry of Agriculture & Farmers Welfare / RBI',
    type: 'central',
    state: null,
    description: 'Short-term credit for farmers at subsidised interest rate (4-7% per annum) for crop cultivation, post-harvest expenses, maintenance of farm assets, and allied activities. Credit limit based on land area and crop pattern.',
    benefitsSummary: 'Subsidised crop loan at 4-7% interest — up to ₹3 lakh without collateral',
    eligibility: { landSizeMaxAcres: null, casteCategories: ['general','obc','sc','st'], incomeLimit: null, ageMin: 18, ageMax: 75, farmingTypes: ['any'] },
    documentsReq: ['Aadhaar card', 'PAN card', 'Land records', '2 passport photos', 'Bank account'],
    applicationUrl: 'https://www.pmkisan.gov.in/kcc.aspx',
    helpline: '1800-180-1551',
    benefitAmount: 300000,
    benefitType: 'credit',
    deadline: null,
    isActive: true,
    fullText: 'Kisan Credit Card provides farmers with affordable credit for their agricultural needs. Interest subvention of 2% for prompt repayment, effectively reducing interest to 4%. Valid for 5 years. Can be used as ATM cum debit card. Covers crop production, ancillary activities, consumption needs.',
  },
  {
    schemeCode: 'PKVY',
    schemeName: 'PKVY (Paramparagat Krishi Vikas Yojana)',
    schemeNameHi: 'परम्परागत कृषि विकास योजना',
    schemeNameMr: 'परंपरागत कृषी विकास योजना',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    type: 'central',
    state: null,
    description: 'Financial assistance to promote organic farming and certification. Cluster-based approach — groups of 50 farmers form a cluster of 50 acres and collectively adopt organic farming. Support for 3 years.',
    benefitsSummary: '₹50,000/hectare over 3 years for organic farming conversion + certification costs',
    eligibility: { landSizeMaxAcres: null, casteCategories: ['general','obc','sc','st'], incomeLimit: null, ageMin: 18, ageMax: null, farmingTypes: ['organic','any'] },
    documentsReq: ['Aadhaar card', 'Land records', 'Group formation certificate', 'Bank account'],
    applicationUrl: 'https://pgsindia-ncof.gov.in',
    helpline: '1800-180-1551',
    benefitAmount: 50000,
    benefitType: 'subsidy',
    deadline: null,
    isActive: true,
    fullText: 'PKVY promotes organic farming through cluster approach. Financial assistance of Rs 50,000 per hectare for 3 years (Rs 31,000 for organic inputs, Rs 8,800 for value addition/packaging, Rs 3,200 for lead farmer, Rs 6,000 for PGS certification). Farmers get PGS-India certification and access to organic markets.',
  },
  {
    schemeCode: 'SMAM',
    schemeName: 'SMAM (Sub-Mission on Agricultural Mechanization)',
    schemeNameHi: 'कृषि यंत्रीकरण उप-मिशन',
    schemeNameMr: 'कृषी यांत्रिकीकरण उप-मिशन',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    type: 'central',
    state: null,
    description: 'Subsidy on purchase of agricultural machinery and equipment. SC/ST and small/marginal farmers get 50% subsidy; others get 40% subsidy. Includes tractors, power tillers, harvesters, sprayers, drip systems.',
    benefitsSummary: '40-50% subsidy on purchase of farm machinery (tractors, harvesters, sprayers)',
    eligibility: { landSizeMaxAcres: null, casteCategories: ['general','obc','sc','st'], incomeLimit: null, ageMin: 18, ageMax: null, farmingTypes: ['any'] },
    documentsReq: ['Aadhaar card', 'Land records', 'Bank account', 'SC/ST certificate (if applicable)'],
    applicationUrl: 'https://agrimachinery.nic.in',
    helpline: '1800-180-1551',
    benefitAmount: null,
    benefitType: 'subsidy',
    deadline: null,
    isActive: true,
    fullText: 'SMAM provides financial assistance for procurement of agricultural machinery by farmers. Subsidy ranges from 40-50% of the machine cost subject to a ceiling. Priority given to SC/ST farmers, small and marginal farmers, women farmers, and North East region. Custom Hiring Centres (CHC) can also be set up with subsidy.',
  },
  {
    schemeCode: 'SOIL_HEALTH_CARD',
    schemeName: 'Soil Health Card Scheme',
    schemeNameHi: 'मृदा स्वास्थ्य कार्ड योजना',
    schemeNameMr: 'माती आरोग्य पत्रिका योजना',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    type: 'central',
    state: null,
    description: 'Free soil testing and soil health card for every farmer once in 2 years. Card contains information on 12 soil quality parameters and fertilizer recommendations specific to the farmer\'s land.',
    benefitsSummary: 'Free soil testing every 2 years with NPK & micronutrient report + fertilizer advice',
    eligibility: { landSizeMaxAcres: null, casteCategories: ['general','obc','sc','st'], incomeLimit: null, ageMin: 18, ageMax: null, farmingTypes: ['any'] },
    documentsReq: ['Aadhaar card', 'Land records'],
    applicationUrl: 'https://soilhealth.dac.gov.in',
    helpline: '1800-180-1551',
    benefitAmount: null,
    benefitType: 'training',
    deadline: null,
    isActive: true,
    fullText: 'Soil Health Card provides information to farmers on nutrient status of their soil along with recommendations on appropriate dosage of nutrients to be applied for improving soil health and its fertility. Scheme covers 14 crore agricultural land holdings across India. Testing done at district and sub-district labs.',
  },
  {
    schemeCode: 'ENАМ',
    schemeName: 'eNAM (Electronic National Agriculture Market)',
    schemeNameHi: 'ई-राष्ट्रीय कृषि बाजार',
    schemeNameMr: 'ई-राष्ट्रीय कृषी बाजार',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    type: 'central',
    state: null,
    description: 'Online trading platform for agricultural commodities. Farmers can sell directly to buyers across India through APMC mandis without middlemen, getting better price discovery.',
    benefitsSummary: 'Sell crops online to buyers across India — better prices, no middlemen',
    eligibility: { landSizeMaxAcres: null, casteCategories: ['general','obc','sc','st'], incomeLimit: null, ageMin: 18, ageMax: null, farmingTypes: ['any'] },
    documentsReq: ['Aadhaar card', 'Bank account', 'Mobile number'],
    applicationUrl: 'https://enam.gov.in',
    helpline: '1800-270-0224',
    benefitAmount: null,
    benefitType: 'training',
    deadline: null,
    isActive: true,
    fullText: 'eNAM integrates 1000+ APMCs across India into one national market. Farmers can get price quotes from multiple buyers, choose best price. Payment directly to bank account. Reduces price manipulation by local traders. Quality assaying available at mandis.',
  },
  {
    schemeCode: 'PMKSY',
    schemeName: 'PMKSY (Pradhan Mantri Krishi Sinchai Yojana)',
    schemeNameHi: 'प्रधानमंत्री कृषि सिंचाई योजना',
    schemeNameMr: 'पंतप्रधान कृषी सिंचाई योजना',
    ministry: 'Ministry of Agriculture & Farmers Welfare / Jal Shakti',
    type: 'central',
    state: null,
    description: 'Subsidy for micro-irrigation systems (drip and sprinkler) to achieve "More Crop Per Drop". SC/ST and small farmers get 55% subsidy on drip irrigation installation; general farmers get 45%.',
    benefitsSummary: '45-55% subsidy on drip/sprinkler irrigation system installation',
    eligibility: { landSizeMaxAcres: null, casteCategories: ['general','obc','sc','st'], incomeLimit: null, ageMin: 18, ageMax: null, farmingTypes: ['any'] },
    documentsReq: ['Aadhaar card', 'Land records', 'Bank account', 'Quotation from approved vendor'],
    applicationUrl: 'https://pmksy.gov.in',
    helpline: '1800-180-1551',
    benefitAmount: null,
    benefitType: 'subsidy',
    deadline: null,
    isActive: true,
    fullText: 'PMKSY promotes micro irrigation to increase water use efficiency. Drip irrigation saves 30-70% water while increasing yield by 20-50%. Components: Accelerated Irrigation Benefits Programme (AIBP), Har Khet Ko Pani, More Crop Per Drop. Farmer applies through state agriculture department portal.',
  },
  // Maharashtra-specific schemes
  {
    schemeCode: 'MH_MAGEL_TYALA_SHETH',
    schemeName: 'Magel Tyala Shettale (Maharashtra)',
    schemeNameHi: 'मागेल त्याला शेततळे योजना (महाराष्ट्र)',
    schemeNameMr: 'मागेल त्याला शेततळे योजना',
    ministry: 'Agriculture Department, Maharashtra',
    type: 'state',
    state: 'Maharashtra',
    description: 'Subsidy for constructing farm ponds (shetkale) for water storage in Maharashtra. 100% subsidy for SC/ST farmers; 50% subsidy (max ₹75,000) for others. Helps in water conservation and drought-proofing.',
    benefitsSummary: '50-100% subsidy for farm pond construction — water storage for dry months',
    eligibility: { landSizeMaxAcres: null, casteCategories: ['general','obc','sc','st'], incomeLimit: null, ageMin: 18, ageMax: null, farmingTypes: ['any'] },
    documentsReq: ['7/12 extract', 'Aadhaar card', 'Bank passbook', 'SC/ST certificate (if applicable)'],
    applicationUrl: 'https://mahaagri.gov.in',
    helpline: '1800-233-4444',
    benefitAmount: 75000,
    benefitType: 'subsidy',
    deadline: null,
    isActive: true,
    fullText: 'Maharashtra government scheme to provide farm ponds to every farmer who applies. Size: 15m x 15m x 3m or larger based on land area. 100% subsidy for SC/ST/ST farmers. 50% subsidy (max Rs 75,000) for other categories. Apply through local Taluka Agriculture Office or online at MahaDBT portal.',
  },
  {
    schemeCode: 'MH_GOPINATH_MUNDE',
    schemeName: 'Gopinath Munde Shetkari Apghat Suraksha Sanyukt Vima Yojana',
    schemeNameHi: 'गोपीनाथ मुंडे शेतकरी अपघात विमा योजना',
    schemeNameMr: 'गोपीनाथ मुंडे शेतकरी अपघात सुरक्षा संयुक्त विमा योजना',
    ministry: 'Agriculture Department, Maharashtra',
    type: 'state',
    state: 'Maharashtra',
    description: 'Accident insurance of ₹2 lakh for Maharashtra farmers aged 10-75 years. Premium paid entirely by Maharashtra government. Covers death and permanent disability due to accidents.',
    benefitsSummary: '₹2 lakh accident insurance — FREE, premium paid by Maharashtra govt',
    eligibility: { landSizeMaxAcres: null, casteCategories: ['general','obc','sc','st'], incomeLimit: null, ageMin: 10, ageMax: 75, farmingTypes: ['any'] },
    documentsReq: ['7/12 extract or 8-A', 'Aadhaar card', 'FIR (in case of accident)', 'Hospital certificate'],
    applicationUrl: 'https://mahaagri.gov.in',
    helpline: '1800-233-4444',
    benefitAmount: 200000,
    benefitType: 'insurance',
    deadline: null,
    isActive: true,
    fullText: 'All farmers in Maharashtra aged 10-75 are automatically covered under this scheme. Premium of Rs 6 per farmer is paid by Maharashtra government. Claim must be filed within 90 days of accident. In case of death: legal heir gets Rs 2 lakh. Permanent total disability: Rs 2 lakh. Permanent partial disability: Rs 1 lakh.',
  },
];

async function main() {
  console.log('Seeding government schemes...');
  let created = 0;
  let skipped = 0;

  for (const scheme of SCHEMES) {
    const existing = await prisma.governmentScheme.findUnique({
      where: { schemeCode: scheme.schemeCode },
    });
    if (existing) { skipped++; continue; }

    await prisma.governmentScheme.create({ data: scheme });
    created++;
    console.log(`  ✓ ${scheme.schemeCode}`);
  }

  console.log(`Done — ${created} created, ${skipped} already existed.`);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
